### ISSUE TITLE
stream_year_last_ndep is set to 2005 instead of 2015 for historical with ctsm1.0.dev093

### ISSUE THREAD

**Issue by olyson** [ESCOMP/CTSM#1004]
### Brief summary of bug

An out of the box historical case using ctsm1.0.dev093 has stream_year_last_ndep set to 2005 instead of 2015

### General bug information

ctsm1.0.dev093

**Does this bug cause significantly incorrect results in the model's science?** Yes

**Configurations affected:** [Fill this in if known.]

--compset HIST_DATM%GSWP3v1_CLM50%BGC-CROP_SICE_SOCN_MOSART_CISM2%NOEVOLVE_SWAV --res f19_g17_gl4

### Details of bug

I ran a short historical simulation with ctsm1.0.dev093 basically out of the box.  The ndep stream seems to be set up wrong for this case.  It's using the updated ndep file correctly, but the stream_year_last_ndep = 2005 and so it's cycling back to 1850 values:

&ndepdyn_nml
 model_year_align_ndep = 1850
 ndep_taxmode = 'cycle'
 ndep_varlist = 'NDEP_month'
 ndepmapalgo = 'bilinear'
 stream_fldfilename_ndep = '/glade/p/cesmdata/cseg/inputdata/lnd/clm2/ndepdata/fndep_clm_hist_b.e21.BWHIST.f09_g17.CMIP6-historical-WACCM.ensmean_1849-2015_monthly_0.9x1.25_c180926.nc'
 stream_year_first_ndep = 1850
 stream_year_last_ndep = 2005
/

I used this to setup the case:

./create_newcase --compset HIST_DATM%GSWP3v1_CLM50%BGC-CROP_SICE_SOCN_MOSART_CISM2%NOEVOLVE_SWAV --res f19_g17_gl4 --case clm50_ctsm10d093_2deg_GSWP3V1_hist --project P93300041 --run-unsupported --machine cheyenne

My case directory is here:

/glade/work/oleson/ctsm1.0.dev093/cime/scripts/clm50_ctsm10d093_2deg_GSWP3V1_hist

### Important output or errors that show the problem

http://webext.cgd.ucar.edu/I20TR/clm50_ctsm10d093_2deg_GSWP3V1_hist/lnd/clm50_ctsm10d093_2deg_GSWP3V1_hist.1995_2014-clm50_ctsm10d089_2deg_GSWP3V1_hist.1995_2014/set1/set1Anom_NDEP_TO_SMINN.png

**Comment by ekluzek** [comment]
Looks like this is the change needed:

``` xml
diff --git a/bld/namelist_files/use_cases/20thC_transient.xml b/bld/namelist_files/use_cases/20thC_transient.xml
index ff56232b..824f63cd 100644
--- a/bld/namelist_files/use_cases/20thC_transient.xml
+++ b/bld/namelist_files/use_cases/20thC_transient.xml
@@ -19,11 +19,11 @@
 <irrigate use_crop=".true." phys="clm4_5"                   >.false.</irrigate>
 
 <stream_year_first_ndep phys="clm4_5" use_cn=".true."   >1850</stream_year_first_ndep>
-<stream_year_last_ndep  phys="clm4_5" use_cn=".true."   >2005</stream_year_last_ndep>
+<stream_year_last_ndep  phys="clm4_5" use_cn=".true."   >2015</stream_year_last_ndep>
 <model_year_align_ndep  phys="clm4_5" use_cn=".true."   >1850</model_year_align_ndep>
 
 <stream_year_first_ndep phys="clm5_0" use_cn=".true."   >1850</stream_year_first_ndep>
-<stream_year_last_ndep  phys="clm5_0" use_cn=".true."   >2005</stream_year_last_ndep>
+<stream_year_last_ndep  phys="clm5_0" use_cn=".true."   >2015</stream_year_last_ndep>
 <model_year_align_ndep  phys="clm5_0" use_cn=".true."   >1850</model_year_align_ndep>
 
 <stream_year_first_popdens phys="clm4_5" cnfireson=".true."   >1850</stream_year_first_popdens>
```

**Comment by ekluzek** [comment]
This is on the release branch, but just for clm4_5 (and technically clm4_0, but that's probably correct).

**Comment by ekluzek** [comment]
I thought this wouldn't change answers unless you ran to December 2005. But, unfortunately it does (I think because at startup it interpolates from the end of the sequence, and the file it uses would be different). As such this change should be done as its own tag.

What I'm seeing is that this case SMS_Ld5_D_P48x1.f10_f10_musgs.IHistClm50Bgc.izumi_nag.clm-month changes answers. And some fields are substantial.

 RMS l2x_Sl_avsdr                     4.0365E-06            NORMALIZED  4.9025E-06
 RMS l2x_Sl_anidr                     2.7681E-07            NORMALIZED  3.6277E-07
 RMS l2x_Sl_avsdf                     2.6628E-06            NORMALIZED  3.2402E-06
 RMS l2x_Sl_anidf                     4.6038E-07            NORMALIZED  5.9131E-07
 RMS l2x_Sl_tref                      9.8281E-04            NORMALIZED  3.6397E-06
 RMS l2x_Sl_qref                      8.7183E-08            NORMALIZED  1.5560E-05
 RMS l2x_Sl_t                         1.0948E-03            NORMALIZED  4.0657E-06
 RMS l2x_Sl_fv                        6.8588E-05            NORMALIZED  2.5407E-04
 RMS l2x_Sl_ram1                      5.4249E-02            NORMALIZED  2.5621E-04
 RMS l2x_Sl_snowh                     1.7065E-09            NORMALIZED  5.8393E-10
 RMS l2x_Sl_u10                       3.7780E-04            NORMALIZED  1.2124E-04
 RMS l2x_Sl_tsrf00                    9.2102E-05            NORMALIZED  3.4868E-07
 RMS l2x_Fall_swnet                   4.5161E-05            NORMALIZED  7.0098E-07
 RMS l2x_Fall_taux                    2.9870E-05            NORMALIZED  2.0801E-04
 RMS l2x_Fall_tauy                    2.9870E-05            NORMALIZED  2.0801E-04
 RMS l2x_Fall_lat                     2.6657E-03            NORMALIZED  1.1415E-04
 RMS l2x_Fall_sen                     2.7624E-03            NORMALIZED  8.2993E-05
 RMS l2x_Fall_lwup                    5.3778E-03            NORMALIZED  1.7279E-05
 RMS l2x_Fall_evap                    1.0659E-09            NORMALIZED  1.1504E-04
 RMS l2x_Fall_flxdst1                 1.6974E-16            NORMALIZED  7.7024E-06
 RMS l2x_Fall_flxdst2                 9.1110E-16            NORMALIZED  7.7024E-06
 RMS l2x_Fall_flxdst3                 2.1364E-15            NORMALIZED  7.7024E-06
 RMS l2x_Fall_flxdst4                 2.0125E-15            NORMALIZED  7.7024E-06
 RMS l2x_Flrl_rofsur                  5.5153E-12            NORMALIZED  2.7701E-06
 RMS l2x_Flrl_rofsub                  2.0844E-15            NORMALIZED  2.5888E-10
 RMS l2x_Fall_voc001                  1.1448E-16            NORMALIZED  1.4874E-07
 RMS l2x_Fall_voc002                  3.2463E-16            NORMALIZED  5.1811E-06
 RMS l2x_Fall_voc003                  2.8781E-15            NORMALIZED  7.3060E-06
 RMS l2x_Fall_voc004                  2.6984E-17            NORMALIZED  6.0935E-07
 RMS l2x_Fall_voc005                  5.7920E-17            NORMALIZED  3.4496E-06
 RMS l2x_Fall_voc006                  2.8219E-17            NORMALIZED  6.0935E-07
 RMS l2x_Fall_voc007                  2.1720E-17            NORMALIZED  3.4496E-06
 RMS l2x_Fall_voc008                  1.0349E-15            NORMALIZED  9.9999E-06
 RMS l2x_Fall_fire001                 2.7822E-18            NORMALIZED  1.8925E-05
 RMS l2x_Fall_fire002                 2.7117E-17            NORMALIZED  1.3728E-05
 RMS l2x_Fall_fire003                 4.2793E-18            NORMALIZED  2.1530E-05
 RMS x2l_Flrr_volr                    2.4020E-09            NORMALIZED  3.0271E-06
 RMS x2l_Flrr_volrmch                 3.0755E-11            NORMALIZED  7.0966E-08
 RMS r2x_Forr_rofl                    3.8271E-14            NORMALIZED  3.7391E-08
 RMS r2x_Flrr_volr                    1.9578E-09            NORMALIZED  3.8191E-06
 RMS r2x_Flrr_volrmch                 4.1736E-11            NORMALIZED  1.4909E-07
 RMS x2r_Flrl_rofsur                  2.3604E-12            NORMALIZED  8.8722E-06
 RMS x2r_Flrl_rofsub                  1.5234E-15            NORMALIZED  8.6796E-10
