### ISSUE TITLE
ndepdata missing for compset ISSP460Clm50BgcCrop

### ISSUE THREAD

**Issue by qhgogogo** [ESCOMP/CTSM#1017]
Dear NCAR Scientist,

While I'm running the compset 'ISSP460Clm50BgcCrop', the 'ndepdata' is missing. I couldn't find it either in the input data server. While for other SSP scenarios, like ISSP126Clm50BgcCrop and ISSP585Clm50BgcCrop, the 'ndepdata' are available. I'm wondering if it is possible for you to upload the 'ndepdata' for  ISSP460Clm50BgcCrop also on the CLM data server?

Thank you,

Han

**Comment by ekluzek** [comment]
Yes, this data is missing, because to construct it a fully coupled simulation with WACCM needs to be done. That's an expensive setup to do. Right now there are no plans to do that for the Tier II CMIP6 SSP scenarios.

A way to get around this for your ISSP460Clm50BgcCrop simulation is to point to a different ndep scenario that does exist. For example point to the ndep file for SSP3-7.0.

**Comment by qhgogogo** [comment]
Thank you, Erik, I will try to use ndep data for SSP3-7.0 then.

**Comment by ekluzek** [comment]
OK, I'm going to close this.

**Comment by qhgogogo** [comment]
Hi, Erik, one more question for this: is it more appropriate to use ndep
data of rcp6.0, for example:  '
fndep_clm_rcp6.0_simyr1849-2106_1.9x2.5_c100810.nc',    for SSP4-6.0?

Thank you!

**Comment by ekluzek** [comment]
That's the older CMIP5 data. It probably makes more sense to use the more recent CMIP6 data. You might want to do some comparisons of the different datasets to decide what might make the most sense.

**Comment by qhgogogo** [comment]
OK, thank you for the answer, I will try both and compare.
