### ISSUE TITLE
Duplicate code in namelist_defaults_ctsm.xml

### ISSUE THREAD

**Issue by glemieux** [ESCOMP/CTSM#1020]
In bringing fates_next_api up to date with ctsm1.0.dev093 I'm seeing what looks like duplicate code in namelist_defaults_ctsm.xml:
https://github.com/ESCOMP/CTSM/blob/9db8e2ec88c231b57b9ad6a46dc2f1601d28e816/bld/namelist_files/namelist_defaults_ctsm.xml#L1122-L1142

I see that the `hgrid` file string is different in the second input; can I assume this is the most recent file or am I misinterpreting the code here?

**Comment by ekluzek** [comment]
Thanks for pointing this out @glemieux. I agree this is duplicated and shouldn't be. This is using the perl parsing methods and so the variable with the most matching attributes is chosen first, and when attributes are the same it will pick the first one given. So by that it should be getting the older file, rather than the newer one, which doesn't sound right.

But, changing which file is pointed to will change answers for the prescribed test case. So we'd want to do that as it's own thing.

**Comment by glemieux** [comment]
Thanks @ekluzek.  Btw I think I found another set of duplicates in namelist_definition_ctsm.xml:
https://github.com/ESCOMP/CTSM/blob/9db8e2ec88c231b57b9ad6a46dc2f1601d28e816/bld/namelist_files/namelist_definition_ctsm.xml#L1634-L1694

**Comment by ekluzek** [comment]
Yep, that looks wrongly duplicated as well.

**Comment by negin513** [comment]
This has been resolved in https://github.com/ESCOMP/CTSM/pull/1187 so I close this issue.
