### ISSUE TITLE
Memory isn't deallocated in some of the init_interp code

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#1032]
This was noticed in looking at #1010. Some of the memory allocated in running init_interp is NOT deallocated afterwards. For example, there are local pointer's that allocate memory that should become allocatable so that memory will be deallocated after it goes out of scope. This is in init_interp.F90.

**Comment by billsacks** [comment]
Copying over some thoughts from #1010 that are relevant here:

As @ekluzek mentioned above: where possible, rather than adding explicit deallocate statements, I think it would be better to change pointer variables to allocatables. Then they will automatically be deallocated. If they are pointers because something else is pointing to them, then they can be declared as `allocatable, target`. At a glance, it looks like this may be possible for the pointers declared in initInterp.F90, but it likely isn't possible for some / all of the pointers in derived types (because you can't use the target attribute for a pointer in a derived type).

My initial thought is that, for every pointer in the init_interp code, we need to either: (a) deallocate it (possibly with a `final` subroutine), or (b) change it to an allocatable.

The main trickiness is that I think some of the derived types that I added, which use pointers, need [`final` subroutines](https://software.intel.com/content/www/us/en/develop/documentation/fortran-compiler-developer-guide-and-reference/top/language-reference/a-to-z-reference/e-to-f/final-statement.html) to deallocate their pointer components.

**Comment by billsacks** [comment]
@ekluzek I'll take this. I'm going to work on it today. I have a hunch that this actually might solve the initial problem, but that there are actually two separate issues and so the second might have masked the first in your testing. More soon....
