### ISSUE TITLE
turn off requirement for prognostic CO2 for using `dribble_crophrv_xsmrpool_2atm`?

### ISSUE THREAD

**Issue by wwieder** [ESCOMP/CTSM#1158]
My understanding is that the xsmr  harvest bug fix (#590 & #610) is still only on when using crop **and** prognostic CO2?

https://github.com/ESCOMP/CTSM/blob/8550666a282186b13c66d73057dec747a3f5bc09/bld/namelist_files/namelist_defaults_ctsm.xml#L496

Can we remove the prognostic CO2 conditional in CTSM5.1?  Should the same be done for CESM2.2?

**Comment by ekluzek** [comment]
Yes, this is on only when co2_type="prognostic" for clm4_5 or clm5_0. This could be changed for clm5_1, so that it's always on when crop is on.

The xml should look something like...

``` xml
<dribble_crophrv_xsmrpool_2atm phys="clm5_1"                use_crop=".true.">.true.</dribble_crophrv_xsmrpool_2atm>
<dribble_crophrv_xsmrpool_2atm co2_type="prognostic" use_crop=".true.">.true.</dribble_crophrv_xsmrpool_2atm>
<dribble_crophrv_xsmrpool_2atm                                         use_crop=".true.">.false.</dribble_crophrv_xsmrpool_2atm>
```

And phys needs to be added to the CLMBuildNamelist.pm. It could be turned on for all versions if that's what we really want. I think it makes sense to keep the previous behavior for clm5_0 though. But, let me know if we don't want that.

**Comment by wwieder** [comment]
You're right Erik, let's keep this as is for CLM5.0, but make it on by
default (with crops) for CTSM5.1.

**Comment by billsacks** [comment]
@dlawrenncar says we should change this for older physics versions, too (clm5_0 and clm4_5). And in that case, we should just go ahead and remove this namelist item.
