### ISSUE TITLE
Incompatible initial conditions for some f09 Hist cases

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/CTSM#1192]
### Brief summary of bug

I ran the `ctsm_sci` test list on a branch off of `ctsm5.1.dev007`. A number of the f09 Hist cases failed, seemingly due to incompatible finidat files.

### General bug information

**CTSM version you are using:** `ctsm5.1.dev007-16-gd44929a7f`. I don't think anything relevant has changed in this tag relative to ctsm5.1.dev007. I haven't checked if this is fixed in dev008, though based on the ChangeLog, it doesn't look like it.

**Does this bug cause significantly incorrect results in the model's science?** No

**Configurations affected:** Observed for a variety of Hist compsets at f09 resolution:
```
    FAIL SMS_Ld5.f09_g17.IHistClm45BgcCruGs.cheyenne_intel.clm-default RUN time=23
    FAIL SMS_Ld5.f09_g17.IHistClm45BgcGs.cheyenne_intel.clm-default RUN time=23
    FAIL SMS_Ld5.f09_g17.IHistClm50Sp.cheyenne_intel.clm-default RUN time=23
    FAIL SMS_Ld5.f09_g17.IHistClm50SpCru.cheyenne_intel.clm-default RUN time=24
```

Here are the f09 tests that passed:

```
    PASS SMS_Ld1.f09_g17.I1850Clm50Sp.cheyenne_intel.clm-default RUN time=22
    PASS SMS_Ld1.f09_g17.I1850Clm50SpCru.cheyenne_intel.clm-default RUN time=22
    PASS SMS_Ld3.f09_g17.I1850Clm50BgcCropCru.cheyenne_intel.clm-default RUN time=33
    PASS SMS_Ld5.f09_g17.I1850Clm45BgcCruGs.cheyenne_intel.clm-default RUN time=35
    PASS SMS_Ld5.f09_g17.I1850Clm45BgcGs.cheyenne_intel.clm-default RUN time=38
    PASS SMS_Ld5.f09_g17.I1850Clm50Bgc.cheyenne_intel.clm-default RUN time=67
    PASS SMS_Ld5.f09_g17.IHistClm45SpGs.cheyenne_intel.clm-default RUN time=50
    PASS SMS_Ld5.f09_g17.IHistClm50BgcCrop.cheyenne_intel.clm-default RUN time=98
```

### Details of bug

I just checked one of the above failures and the issue was that init_interp seemed to be needed, but use_init_interp wasn't set for the case. I should note that my testing was done from a branch that I'm using to test pio2, but I don't think anything relevant has changed on this branch, so I assume the same problem exists on master.

@ekluzek the new ctsm_sci test list seems valuable in picking up issues like this. I wonder if we should have a rule that we run this test list (without baseline comparisons) whenever we remake many of the initial conditions and/or surface datasets?

**Comment by ekluzek** [comment]
I looked into this because I thought that new IC files were needed. But, it's just that use_init_interp=T must be set for transient simulations even if it's not needed for the non-transient counterpart. So it needs to check if IC and if transient is set it needs to set use_init_interp to true even if it's not needed otherwise.

**Comment by ekluzek** [comment]
I ran into this again because I ran the ctsm_sci test list and the Hist tests failed because of this.

**Comment by ekluzek** [comment]
These are the ctsm_sci tests that failed for me:

SMS_Ld5.f09_g17.IHistClm45BgcCru.cheyenne_intel.clm-default		
SMS_Ld5.f09_g17.IHistClm50Sp.cheyenne_intel.clm-default		
SMS_Ld5.f09_g17.IHistClm50SpCru.cheyenne_intel.clm-default

Note, that the f19 Hist tests worked fine, because use_init_interp was set to true for them.
