### ISSUE TITLE
In nuopc cap: don't do math on garbage ndep fields when not receiving ndep from coupler

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/CTSM#1235]
I noticed that the nuopc cap doesn't check the logical variable `ndep_from_cpl` when importing the ndep fields:

https://github.com/ESCOMP/CTSM/blob/c4cf1205bdd835b2cccbffe184e5d71858d58252/src/cpl/nuopc/lnd_import_export.F90#L540-L546

I don't understand how this works in the common case where we are *not* getting ndep from the atmosphere. For example, would the missing fields trigger a premature return (via the ChkErr return value)? Or would forc_ndep_grc get filled with garbage? Either way seems potentially problematic.

@mvertens can you provide input here?

**Comment by ekluzek** [comment]
@billsacks I think you are right. The chkErr should trigger an error and abort.

 If they don't I think it's actually OK in that forc_ndep will be filled with garbage, but the setting of ndep_from_cpl will tell it to read from file rather than using the values passed down.

We should try out a case where we test this. We need a F compset with WACCM so that we know ndep is passed down. I suppose the test case that failed for Chris, but with nuopc cap should do it.

**Comment by ekluzek** [comment]
It looks like what will happen is that it won't find the ndep data and hence will ignore setting it. Then ndep will be set to garbage. But, ndep_from_cpl is set correctly so it'll read it from files. And it looks like it should also work in the case when ndep is sent down.

So I think it's OK. Although you are right that it's going to be setting a field to garbage, that maybe it shouldn't be doing.

**Comment by billsacks** [comment]
Thanks for your thoughts @ekluzek . I was in the middle of writing something similar. My recollection is that state_getimport can safely be called on non-existent fields (@mvertens am I remembering this right?). I do think it could be a problem to try to do math on a garbage field, so we should still fix this. But it probably isn't causing any problems as is. I'm going to change the title and type accordingly.

@mvertens it seems like the right fix would be to wrap this block of code in a conditional on `ndep_from_cpl`. But I'm wondering if there's a reason you avoided doing that initially.
