### ISSUE TITLE
CLM future climate data

### ISSUE THREAD

**Issue by qhgogogo** [ESCOMP/CTSM#1369]
I'm trying to run CLM under future scenario with COMPSET 'ISSP245Clm50BgcCrop', but I couldn't find corresponding forcing data on Cheyenne. Could you help me find those future climate data on Cheyenne?

Thanks,

Han

**Comment by olyson** [comment]
There is also coupler history data available for one SSP245 ensemble member to force CLM in CPLHIST mode here:

/glade/p/datashare/oleson/shared_data/CMIP6/cpl_hist/b.e21.BSSP245cmip6.f09_g17.CMIP6-SSP2-4.5.102

Since you apparently have cheyenne access, you should be able to access this directory.  Otherwise, email me at oleson at ucar dot edu and I'll send you the Globus link.

I believe the data is in daily files which need to be concatenated to the monthly files that CPLHST mode requires, after you've downloaded the data and untarred the files.
I've put a script in the "CODE" subdirectory that will do that (concat_cpl_hist_mon.csh). There is also an example of how to run that script there (concat.command).

**Comment by qhgogogo** [comment]
Thank you, Dr. Wieder and Dr. Oleson.

Dr. Oleson, I have Cheyenne access but I don't have permission to get
access to /glade/p/datashare/oleson/shared_data/CMIP6, could you send me
the Globus link or other downloadable link?

Best regards,
Han

**Comment by olyson** [comment]
I've sent you the link.

**Comment by wwieder** [comment]
were you able to get your simulations to work @qhgogogo ?

**Comment by billsacks** [comment]
Closing for now; @qhgogogo feel free to reopen if you still need help.
