### ISSUE TITLE
Spinup: Create NEON initial conditions files

### ISSUE THREAD

**Issue by wwieder** [ESCOMP/CTSM#1385]
As part of the NCAR-NEON project we need to provide initial conditions (restart files for Jan-2018) for each site.  

Let's start by running a SASU spinup from cold start for each site, looping over data 2018-2020.
@negin513 can you talk to @olyson for how to best do this?

We'll need to check the steady state thresholds for this, which can build on this script https://github.com/ESCOMP/CTSM/blob/master/tools/contrib/SpinupStability.ncl

This is connected to #1354.

**Comment by ekluzek** [comment]
@wwieder in order to do a SASU spinup we'll need to get one of the CN matrix branches updated to ctsm5.1.dev039. Or wait until CN matrix is on the trunk.

You probably want to start with a normal spinup and get the protocol or scripts setup to do that first. The AD spinup is the first step anyway, so the final version will just add some extra steps.

**Comment by wwieder** [comment]
Perfect.  @negin513 let's just start with the 'normal' AD spinup.  I typically run for 400 years in AD and 200 years in postAD.  This likely isn't necessary (except for some of the cold sites), but it's easier and relatively inexpensive to be safe on this...

**Comment by wwieder** [comment]
@jedwards4b will provide these with input_data on the next tag that gets made for the container.  

The wrapper script (#1444) that @negin513 created and @jedwards4b modified will also have options to run the:
- full transient case (starting for the postAD restart file), as well as with just the 
- latest data (starting from the end of the transient simulation for when new data are available from NEON).
