### ISSUE TITLE
landuse.timeseries_0.9x1.25_SSP3-7.0_16pfts_Irrig_CMIP6_simyr1850-2100_c190214.nc is missing on inputdata

### ISSUE THREAD

**Issue by olyson** [ESCOMP/CTSM#1428]
A user is looking for a file on:

https://svn-ccsm-inputdata.cgd.ucar.edu/trunk/inputdata/lnd/clm2/surfdata_map/release-clm5.0.18/

The file is

landuse.timeseries_0.9x1.25_SSP3-7.0_16pfts_Irrig_CMIP6_simyr1850-2100_c190214.nc

It is available at

/glade/p/cesmdata/cseg/inputdata/lnd/clm2/surfdata_map/release-clm5.0.18

but not on svn.

Can someone add this (I don't have permission)?

**Comment by ekluzek** [comment]
I just did that for that file.

I'll also check if there are other files missing.

**Comment by olyson** [comment]
Thanks Erik!

**Comment by ekluzek** [comment]
A bunch of other files from that directory were missing, and all of the .log files. So I'm just entering everything in that directory.  A few of the files with different dates might have been missed because they were special adds. Some of the files with the Valentine's date should have been there previously, and it's disconcerting that they weren't. I'm not sure how to check why some files were included and others were missed though. Here's a list of the other missing files:

lnd/clm2/surfdata_map/release-clm5.0.18/landuse.timeseries_0.9x1.25_hist_16pfts_Irrig_CMIP6_simyr1850-2015_c190214.nc
lnd/clm2/surfdata_map/release-clm5.0.18/landuse.timeseries_0.9x1.25_hist_78pfts_CMIP6_simyr1850-2015_c190214.nc
lnd/clm2/surfdata_map/release-clm5.0.18/landuse.timeseries_0.9x1.25_SSP1-1.9_78pfts_CMIP6_simyr1850-2100_c190214.nc
lnd/clm2/surfdata_map/release-clm5.0.18/landuse.timeseries_0.9x1.25_SSP4-3.4_78pfts_CMIP6_simyr1850-2100_c190214.nc
lnd/clm2/surfdata_map/release-clm5.0.18/landuse.timeseries_10x15_hist_16pfts_Irrig_CMIP6_simyr1850-2015_c190214.nc
lnd/clm2/surfdata_map/release-clm5.0.18/landuse.timeseries_10x15_hist_78pfts_CMIP6_simyr1850-2015_c190214.nc
lnd/clm2/surfdata_map/release-clm5.0.18/landuse.timeseries_10x15_SSP3-7.0_78pfts_CMIP6_simyr1850-2100_c190228.nc
lnd/clm2/surfdata_map/release-clm5.0.18/landuse.timeseries_10x15_SSP4-3.4_78pfts_CMIP6_simyr1850-2100_c190228.nc
lnd/clm2/surfdata_map/release-clm5.0.18/landuse.timeseries_1.9x2.5_SSP1-2.6_78pfts_CMIP6_simyr1850-2100_c190228.nc
lnd/clm2/surfdata_map/release-clm5.0.18/landuse.timeseries_1.9x2.5_SSP2-4.5_78pfts_CMIP6_simyr1850-2100_c190228.nc
lnd/clm2/surfdata_map/release-clm5.0.18/landuse.timeseries_1.9x2.5_SSP3-7.0_78pfts_CMIP6_simyr1850-2100_c190228.nc
lnd/clm2/surfdata_map/release-clm5.0.18/landuse.timeseries_1.9x2.5_SSP4-3.4_78pfts_CMIP6_simyr1850-2100_c190228.nc
lnd/clm2/surfdata_map/release-clm5.0.18/landuse.timeseries_1.9x2.5_SSP5-8.5_78pfts_CMIP6_simyr1850-2100_c190228.nc
lnd/clm2/surfdata_map/release-clm5.0.18/landuse.timeseries_1x1_brazil_hist_16pfts_Irrig_CMIP6_simyr1850-2015_c190214.nc
lnd/clm2/surfdata_map/release-clm5.0.18/landuse.timeseries_1x1_brazil_hist_78pfts_CMIP6_simyr1850-2015_c190214.nc
lnd/clm2/surfdata_map/release-clm5.0.18/landuse.timeseries_1x1_smallvilleIA_hist_78pfts_CMIP6_simyr1850-1855_c190214.nc
lnd/clm2/surfdata_map/release-clm5.0.18/landuse.timeseries_48x96_hist_16pfts_Irrig_CMIP6_simyr1850-2015_c190214.nc
lnd/clm2/surfdata_map/release-clm5.0.18/landuse.timeseries_48x96_hist_78pfts_CMIP6_simyr1850-2015_c190214.nc
lnd/clm2/surfdata_map/release-clm5.0.18/landuse.timeseries_4x5_hist_16pfts_Irrig_CMIP6_simyr1850-2015_c190214.nc
lnd/clm2/surfdata_map/release-clm5.0.18/landuse.timeseries_4x5_hist_78pfts_CMIP6_simyr1850-2015_c190214.nc
lnd/clm2/surfdata_map/release-clm5.0.18/landuse.timeseries_ne30np4_hist_16pfts_Irrig_CMIP6_simyr1850-2015_c190303.nc
lnd/clm2/surfdata_map/release-clm5.0.18/landuse.timeseries_ne30np4_hist_78pfts_CMIP6_simyr1850-2015_c190303.nc
lnd/clm2/surfdata_map/release-clm5.0.18/surfdata_1x1_brazil_hist_78pfts_CMIP6_simyr2000_c190214.nc
lnd/clm2/surfdata_map/release-clm5.0.18/surfdata_48x96_hist_78pfts_CMIP6_simyr2000_c190214.nc
lnd/clm2/surfdata_map/release-clm5.0.18/surfdata_5x5_amazon_hist_78pfts_CMIP6_simyr2000_c190214.nc
lnd/clm2/surfdata_map/release-clm5.0.18/surfdata_ne30np4_hist_78pfts_CMIP6_simyr1850_c190303.nc

**Comment by ekluzek** [comment]
OK, closing this. Feel free to open another issue with other missing data.
