### ISSUE TITLE
Add support for using "black" as a python formatter to our python coding process

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#1471]
We'd like to transition to using "black" as a python code formatter to our python coding process. Using it as a formatter will make sure we comply with PEP8, and keep our code in a consistent format. We talked about this in our CSEG meeting and CAM and others thought that there was a need for such a tool. pylint is still worthwhile in checking for issues, but we need a separate tool for formatting the appearance of code. Having a tool to do the formatting means we don't have to waste time working on appearance and can just let the formatter take care of consistent look and feel. We want to apply to this to the python modules under our "python" directory in CTSM. We won't require it of other python code, especially right now, and especially don't think the code in "tools/contrib" needs to worry about this.

There are two steps we think are important to accomplish this.

- Add a target to the python directory Makefile for "black" to run the python codes through black.
- Add a github action to check that python code has been run through black and if not trigger an error.

The first one should be straight forward as it will be similar to the pylint check in the python directory.

The second we aren't quite sure how it will work. What we'd like it to do is to prevent a PR from being approved if the "black check" operation isn't clear. This would be similar to the checkbox PR checker we already have in place. We think looking at how the action is done for the checkbox checker should help in figuring it out. Documentation on github for actions should also help. And black has some advice on github actions here...

https://black.readthedocs.io/en/stable/integrations/github_actions.html

I also see a lot of help on this from doing a google search for this, so there's likely many different examples of how to do this and we just need to pick the one for the way we do it.

@billsacks also suggests checking with Jesse in CAM and Jason Boutte from LBL.

**Comment by ekluzek** [comment]
I added a target to the makefile to run the python code under python/ctsm through black. That was easy to add, and it does work.

**Comment by billsacks** [comment]
I just came across https://pre-commit.com/ , referenced by https://github.com/readme/guides/code-review . I haven't looked carefully, but it looks like it could be helpful for integrating black and other checkers / formatters into pre-commit hooks in a robust way.

**Comment by ekluzek** [comment]
black is available on cheyenne if you run ncar_pylib. I was able to install it on my laptop with "brew" really easily. And I got CGD-ISG to install it on "andre.cgd.ucar.edu" as part of

module load lang/python/3.7.0

They will start to propagate black to other systems in the coming days and weeks.

**Comment by ekluzek** [comment]
I did some testing in one of my own repositories for github actions to run black and found the following to work. I think we would modify below just slightly for our purposes....

.github/workflows/black.yml 
``` yaml
name: push black workflow
#
# Run the python formatting in check mode
#
on: push

jobs:
  black-check:
     runs-on: ubuntu-latest
     steps:
        - uses: actions/checkout@v1
        - uses: jpetrucciani/black-check@master
          with:
             path: python
             black_flags: '--exclude (\./F90|\.pl)'

```

**Comment by billsacks** [comment]
I should have added: one of the issues raised by https://github.com/readme/guides/code-review is how to deal with changes over time in the rules and/or tools you are applying to your code. e.g., imagine this situation:
- As of ctsm5.2.0, we were using black v. 1.0 with whatever rules it applies
- Then black moves ahead to v. 2.0, with some changes in its formatting rules. This coincides in time with (say) ctsm5.3.0.

If you have some ctsm branches after ctsm5.3.0 and some before that point, which version of black should you have installed? Either choice will give incorrect results for some of your branches. Similarly, what if some dev machines have updated to black 2.0 while others are still at black 1.0?

The solution, as I understand it, is to make sure that your checker / formatter is versioned in your repo alongside your code – or at least the configuration file controlling the behavior of the checker(s) / formatter(s). We do this for some extent with pylint (by versioning a pylintrc file), though I think it's not perfect, because I think there is still some behavior dependence on the version of pylint you have installed. My gut sense is that the problem is somewhat more important for formatters, where different people having different versions could lead to a huge amount of code churn / battles.

I guess that – given that I'm not personally convinced that we're solving an important problem with "black" – I remain a bit worried about situations like this where "black" could cause as many or more issues than it solves. That's not necessarily to say that we shouldn't adopt it (since others seem very keen to do so), but I do feel it's important to consider issues like this and how we'll solve them, and in doing so, evaluate whether it's really worth the trouble.

**Comment by billsacks** [comment]
I just started playing around with black a very little bit, running it on one (somewhat large) python file via an editor extension. My initial feelings are:
- I have no objection to the changes it made. I didn't see them as necessarily better or worse than how things were already. I guess that's sort of the point, but it reinforces the feeling that I'd want any process involving black to do no harm, so that it's not doing more harm than good.
- If we adopt black, I'm thinking that I'll personally probably integrate it into my editor, so that it's run automatically on save. My initial thinking is that that is the lowest friction way to do it. Doing it this way means you need to trust it, but I feel that's reasonable: if we don't have 100% trust in black, then I feel that we shouldn't adopt it, because I think it's unreasonable to expect anyone to review all of the changes black makes. (To be clear: I *am* comfortable placing 100% trust in black.)

**Comment by ekluzek** [comment]
OK, nice article. @rgknox and I relate to the content of the article as most of our last code review discussion was about white space formatting.

Your point about the version of the formatter is a good one. We can manage that by specifying the version of the black-checker (which in turn specifies the version of black) in the github action for it. The action is in the repository, so that part is robust.

Your point on versioning is also important because the people behind black only claim it being in the "beta" stage, so formatting changes can and will happen. Since, it is a formatter I'm pretty sure that such changes are going to be rare though.

Now, the other side are the versions of black that are available for the user. And the version on my mac on on CGD andre is newer by a major version than the version you get on cheyenne with "ncar_pylib". You can get a newer version on cheyenne by using the conda module and installing it.

Anyway, I used the two versions and looked to see how they differed. For the 20k lines of python code in CTSM I only saw a removal of a single space

```
33c33
<     """Build the CTSM namelist """
---
>     """Build the CTSM namelist"""
```

When I add the cime python code as well as FATES which adds up to 91k lines of python code I see similar changes. So differences do exist between major versions -- but they seem to be minor and less than a fraction of a percent. Which is all to say to me that it's pretty robust.

Using black also showed me that I can target a python version and it will point out problems relative to that version. And as such it pointed out files that wouldn't work with python-3, which I thought was a really nice feature!

So I am pretty sold on black at this point. But, even so I do want to adopt it in steps and have it prove it's worth. Thanks again to @negin513 for finding it.

**Comment by ekluzek** [comment]
Black is now out of beta and they have their official version. Release 22.1.0. I think this means that they are less likely to make changes to behavior.
