### ISSUE TITLE
Suggested cleanup in CropPhenology(): Removing duplicated sowing code

### ISSUE THREAD

**Issue by samsrabin** [ESCOMP/CTSM#1479]
[At tag ctsm5.1.dev054 (dfe9d66)]

In the `CropPhenology()` subroutine in `CNPhenologyMod.F90`, the code in the `if` block beginning at line 1925 and the following `else if` (beginning at line 1988) both sow crops. The difference in the conditionals is that the former looks for two temperature conditions (lines 1926–1927) to be satisfied during the sowing window, whereas the latter relaxes that on the last day of the window.

There's only one difference between the code of those blocks. It happens for C4 crops (corn, sugarcane, _Miscanthus_, and switchgrass); i.e.:
```
if (ivt(p) == ntmp_corn .or. ivt(p) == nirrig_tmp_corn .or. &
    ivt(p) == ntrp_corn .or. ivt(p) == nirrig_trp_corn .or. &
    ivt(p) == nsugarcane .or. ivt(p) == nirrig_sugarcane .or. &
    ivt(p) == nmiscanthus .or. ivt(p) == nirrig_miscanthus .or. &
    ivt(p) == nswitchgrass .or. ivt(p) == nirrig_switchgrass) then
```
Here's what happens in the `if` block (lines 1953–1954):
```
gddmaturity(p) = max(950._r8, min(gdd820(p)*0.85_r8, hybgdd(ivt(p))))
gddmaturity(p) = max(950._r8, min(gddmaturity(p)+150._r8, 1850._r8))
```
And here's what happens in the `else if` block (line 2005):
```
gddmaturity(p) = max(950._r8, min(gdd820(p)*0.85_r8, hybgdd(ivt(p))))
```
(I'm assuming this difference in behavior is intentional.) 

This code section would benefit from some consolidation. For instance: have logicals representing the outcomes of the `if` and `else if` conditions, combine those blocks (into, e.g. `if (logical_1 .or. logical_2)`), and then only adding code to distinguish between the behavior for C4 crops:
```
if (ivt(p) == ntmp_corn .or. ivt(p) == nirrig_tmp_corn .or. &
    ivt(p) == ntrp_corn .or. ivt(p) == nirrig_trp_corn .or. &
    ivt(p) == nsugarcane .or. ivt(p) == nirrig_sugarcane .or. &
    ivt(p) == nmiscanthus .or. ivt(p) == nirrig_miscanthus .or. &
    ivt(p) == nswitchgrass .or. ivt(p) == nirrig_switchgrass) then

   gddmaturity(p) = max(950._r8, min(gdd820(p)*0.85_r8, hybgdd(ivt(p))))

   if (logical_1) then
      gddmaturity(p) = max(950._r8, min(gddmaturity(p)+150._r8, 1850._r8))
   end if

end if
```
This would also provide the space for a comment explaining the difference in behavior, which isn't obvious to me. At first I thought it was "require an extra 150 GDD (up to 1850 GDD max) for crops sown when it was colder than 'preferred' by the crop type," but that's not right, because the extra 150 GDD only gets added when the temperature conditions _are_ satisfied.

**Comment by wwieder** [comment]
Thanks for looking into this @samsrabin. 

I'm assuming this would not change model behavior, and be a bit for bit (BFB) change?
If so, go ahead and make the changes you suggest in a pull request and @ekluzek or @negin513 can do the testing and bring the change to main.

Let us know if you need help or extra guidance on this.

**Comment by samsrabin** [comment]
Exactly, it should result in bit-for-bit identical outputs. I'll submit a pull request shortly.

**Comment by billsacks** [comment]
Thanks a lot for opening this issue @samsrabin , and for taking on making the change. I know yesterday I said this might not be worth fixing, but actually, given that the fix is relatively straightforward and the duplication is potentially a real problem, I think that fixing this is worthwhile. So thanks for this.

It looks to me like there is similar duplication in the winter cereals block; would you be willing to fix that block in the same way while you're doing this?

Regarding the one line difference: I was on a call with @slevisconsulting earlier today and asked if he remembered the history of this; he did not. This goes back as far as I looked in the CLM code history. Unless anyone wants to take the time to dig into it to understand it better, I agree that we should assume that it was intentional, even if we aren't able to explain it well.

**Comment by samsrabin** [comment]
Sure, makes sense. I'll have a look at the winter cereals block tomorrow and push changes to my branch in the pull request.
