### ISSUE TITLE
For water tracers / isotopes, do we need to handle lake mixing?

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/CTSM#1516]
Inspired by some thoughts in #518 (in particular, see https://github.com/ESCOMP/CTSM/issues/518#issuecomment-938991932): Do we need to handle the mixing of water tracers / isotopes between lake layers? I looked through the CLM4.0 isotope code and couldn't see anything like this there. Intuitively, it seems to me like this would be important to get the short-term (e.g., diurnal to seasonal) temporal variability of tracer / isotope fluxes from lakes correct, but maybe that isn't a first-order-important issue? By *not* handling this mixing, it seems like the isotopic ratios in the top lake layer – and thus the isotopic ratios of any fluxes from the lake – would adjust more quickly to the isotopic ratios of incoming precipitation than they do in reality (where mixing with deeper layers leads to a dampening of temporal variability).

@dlawrenncar @nusbaume @davidnoone

**Comment by nusbaume** [comment]
Hi @billsacks ,

From a real-world physics standpoint the water isotope values will absolutely be impacted by vertical mixing in lakes.  However, I also know that parameterizing mixing processes can be a non-trivial exercise with various levels of complexity, which could be why it wasn't implemented in CLM4.0 (we likely had bigger issues to tackle at the time).  Plus I am not sure how many observations of water isotopes in lake water and the surrounding environments there are to help validate what impact vertical mixing might have.

Is any sort of vertical mixing done in CTSM for quantities like carbon or lake water temperature?  If so then we can likely apply that same mixing parameterization to the water tracer/isotope masses.  Otherwise I might vote to just have the same setup as CLM4 for now, and then once that is working @davidnoone, myself, and others can see about implementing an acceptable vertical mixing parameterization  (which would also give us the chance to search for and collect the necessary isotopic observations).  

Anyways, thats my $0.02 on the topic.

**Comment by billsacks** [comment]
Thanks a lot @nusbaume . That makes sense. The lake model has evolved significantly since CLM4, though I don't know a lot about the details. See https://escomp.github.io/ctsm-docs/versions/master/html/tech_note/Lake/CLM50_Tech_Note_Lake.html#overview-of-changes-from-clm4 for some information. The lake model does include temperature adjustments between layers, which according to the tech note includes convective mixing, but I don't know enough to say whether this could be transferred over to mixing of other quantities. I don't think there is any mixing of carbon or other constituents within the lake model currently.

Given your reply, I'm going to close this as resolved for now. We can open a new issue to deal with this if someone feels it's important to handle tracer mixing within lakes, but given your thoughts, it sounds like this is not likely to be a high priority.
