### ISSUE TITLE
Change PTSMODE testing from f45 to: T42, f09 and f19 resolutions

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#1584]
PTSMODE testing is just done at f45 resolution currently. f45 was just chosen to have a small global grid for testing, since it should work for any regular 2D structured grid. Something unique in PTSMODE for nuopc is that it requires domain files, while they are not required for other cases. For going forward we only want to support a limited number of domain files for PTSMODE.

The one resolution that SCAM uses PTSMODE for is T42, since a spectral resolution is required. CTSM users sometimes debug by running PTSMODE for a single point from the global grid, so I propose that we support the two standard workhorse resolutions of f09 and f19.

Since, now only a limited number of resolutions will be allowed, we might as well test for all of them. These are small short tests and we mainly want to see that they function.

**Comment by ekluzek** [comment]
@swensosc and @olyson I think you are one of the users of this functionality. Does this change sound OK to you?

**Comment by olyson** [comment]
Sounds reasonable to me.

**Comment by billsacks** [comment]
@ekluzek since the additional resolutions won't add any code coverage, I'd suggest that we have a single test in aux_clm with additional tests (if warranted) in the clm_science test list. I know these are small, short tests, but the test build time is impacted by each additional test. I really like the strategy of keeping aux_clm focused on providing full code coverage, with resolution coverage provided by clm_science. Does that seem reasonable, or do you see a reason why including multiple resolutions of PTSMODE testing in aux_clm is important?

**Comment by ekluzek** [comment]
@billsacks your suggestion makes sense to me. And I like it as you are right there would be three builds instead of one with my suggestion. We don't run clm_science that often, but you are right that's what it's purpose is.

So the standard test should be for T42, and f09 and f19 in clm_science.

**Comment by ekluzek** [comment]
This was done in ctsm5.2.0 so closing.
