### ISSUE TITLE
To run mkmapdata.sh, need to set CSMDATA env variable, improve the error message for this issue

### ISSUE THREAD

**Issue by slevis-lmwg** [ESCOMP/CTSM#1599]
### Brief summary of bug

`./mkmapdata.sh -r 4x5` was failing for me on cheyenne and @ekluzek pointed out that I needed .tcshrc and .cshrc files with appropriate env. settings.

### General bug information

**CTSM version you are using:** ctsm5.1.dev069-7-g57175712e

**Does this bug cause significantly incorrect results in the model's science?** No

### Details of bug

`./mkmapdata.sh -r 4x5`
was giving me

```
unrecognized arguments: scripgriddata
Make sure CSMDATA environment variable is set correctly
```

`echo $SHELL`
returns
`/bin/tcsh`
...so I copied @ekluzek 's  .cshrc file and sourced his .tcshrc file. Then mkmapdata.sh worked. So now I have also copied his .tcshrc.

**Comment by slevisconsulting** [comment]
@ekluzek this is resolved for me. Let me know if it's ok to close it.

**Comment by ekluzek** [comment]
@slevisconsulting we just need to improve the error message so it's obvious what you need to do. The one thing that the user needs to do is set the CSMDATA env variable. The help for the script says you can optionally set CSMDATA, but it turns out that it requires it to be set. So it should list it as required and have a high level check if it's not set, and die with a clear error on what you need to do to fix it.

**Comment by ekluzek** [comment]
Closing as a wontfix since mksurfdata_esmf means this doesn't matter.
