### ISSUE TITLE
Decide on how and if our python unit-testing for CTSM can be run standalone

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#1642]
Currently the tests under python/ctsm/test can only be easily run through the test harness python/run_ctsm_py_tests. You can't easily just run one of the unit test files. @negin513 did some work to add some extra import and path handling to the top of the file as well as a `if __name__ == "__main__":` at the end so that you can run just the one unit test file. It adds some complexity, but might be useful when debugging just one module. A concern is that adding extra complexity to the top of each unit test fie gets in the way when run under the test harness that runs all of them. There are also different ways of handling this. As a group I'd like to discuss this and decide how we'd like to handle it.

Some discussion on this is here with two comments:

https://github.com/ESCOMP/CTSM/pull/1461#issuecomment-1025172178

A stackoverflow answer pointed to in that discussion recommends that the way to run a test standalone is with this type of thing:

python -m unittest <filename>

That might be a good compromise here. In any case I'd like to discuss this as a group.

**Comment by billsacks** [comment]
I want to make sure we're properly distinguishing between two points here:

(1) Can you run the unit test scripts directly from the command line?

This is already possible for at least some of the scripts... my intention was that it should be possible for all, but I may have missed some. e.g.:

```
[~/ctsm/ctsm0/python] (master=)
$ ./ctsm/test/test_unit_lilac_build_ctsm.py
```

The `__name__ == "__main__"` check is needed for this, and I support that.

(2) Can you run the unit test scripts from any arbitrary directory?

This is what I was questioning (at least given the current implementation), because I don't love having every unit test file do an unconditional sys path manipulation, and I feel like it's reasonable to need to run a given unit test file from the root of the python directory.

But as I said here https://github.com/ESCOMP/CTSM/pull/1461#issuecomment-1034224298

> I don't feel strongly about this. My preference would be to stay consistent with standard python unit testing practice. I'm not positive what that is, to be honest, but my sense is that sys path manipulation is generally frowned upon unless it's really needed... but I could be wrong. Anyway, I'm fine with letting you make the call here.

**Comment by ekluzek** [comment]
I'm going to close this as a won't fix because I now see the ability to run single tests via a pattern sent to run

./run_ctsm_py_tests -p $file

is sufficient. And Looking at the latest CTSM I see this works for all tests with a general check

``` tcsh
foreach file ( ctsm/test/test_*.py )
   ./run_ctsm_py_tests -p $file
end
```

Which must mean that we have the proper closing for all of them.

On the point "2" above about directory manipulation. That makes sense as well, don't mess with changing directories unless it's needed.
