### ISSUE TITLE
Winter crop sowing: Incorrect check for minimum temp. criterion?

### ISSUE THREAD

**Issue by samsrabin** [ESCOMP/CTSM#1656]
### Brief summary of bug

A `<=` should probably be a `>` in a comparison of `a5tmin` (5-day running mean of min 2-m temperature) to `minplanttemp` (minimum planting temperature, PFT-specific).

### General bug information

**CTSM version you are using:** ctsm5.1.dev077

**Does this bug cause significantly incorrect results in the model's science?** Not yet (winter cereals disabled)

**Configurations affected:** Any configuration running winter cereals (so, none, except work in development).

### Details of bug

I haven't had time to look into this for an innocuous explanation, but: Shouldn't line 1847 here be `>` instead of `<=`?

https://github.com/ESCOMP/CTSM/blob/d6b233433bc34977f72920f9660b3792bb128faa/src/biogeochem/CNPhenologyMod.F90#L1845-L1850

Compare with what seems to be the correct behavior, for crops other than winter cereals (here it's `a10tmin`):

https://github.com/ESCOMP/CTSM/blob/d6b233433bc34977f72920f9660b3792bb128faa/src/biogeochem/CNPhenologyMod.F90#L1878-L1885

**Comment by billsacks** [comment]
I'm not very familiar with this code, so I'm just speculating here, but I wonder if this was intentional to have a rule that winter crops are planted once the temperature drops _below_ a particular temperature threshold, as opposed to the typical (spring-planted crop) rule of the temperature rising _above_ a particular threshold. If so, the use of a variable called `minplanttemp` is certainly counter-intuitive, but I wonder if that was done just to keep the parameter name the same for winter crops even though the meaning is different.

Again, I'm just speculating here....

**Comment by samsrabin** [comment]
Ah yep, that makes sense. Perhaps it'd be a good idea to add a comment there.

**Comment by billsacks** [comment]
Great, thanks for the input @jyotisinghkashyap . @samsrabin I'm going to go ahead and close this. If you want to add a comment in your open PR, that would be welcome.
