### ISSUE TITLE
subset_data enhancement

### ISSUE THREAD

**Issue by ka7eh** [ESCOMP/CTSM#1659]
I was trying to run `subset_data`, but noticed it's missing an entry point (e.g. `if __name__ == __main__`) and cannot be called from the command line.

I was also wondering if it's possible to make [`DEFAULT_FILE`](https://github.com/ESCOMP/CTSM/blob/master/python/ctsm/subset_data.py#L78) configurable via args so we can overwrite it for other machines?

I have these changes on my local machine. If they are ok, I can submit a PR.

Btw, is there a style/linting/best practices guide I should use? I took a quick look around and didn't find anything right away.
One more thing: what's the minimum supported version of python for CTSM?

**Comment by negin513** [comment]
Dear Kaveh, 
Thanks for your email and suggestion to improve subset_data.py. I am glad you asked these questions. 

> I was trying to run subset_data, but noticed it's missing an entry point (e.g. `if __name__ == __main__`) and cannot be called from the command line.

subset_data.py can **only** be used via top level skeleton code called [subset_data](https://github.com/ESCOMP/CTSM/blob/master/tools/site_and_regional/subset_data). So it is intentional that we don't have `if __name__ == __main__` anywhere in subset_data.py. 
If you look under `tools/site_and_regional` you should be able to find subset_data (without .py) and run it smoothly.
 
I know this is confusing and it was a highly debated point in the PR discussion and several meetings. 
However, at the end SE decided to have a top level empty skeleton code without extension (.py) that calls .py code. **For the record I agreed with you and in the original versions of the code the user was able to run either subset_data.py and/or subset_data.** 
 So for all CTSM python codes we want to have an empty skeleton code without `.py` that calls the `main` from the real python code (with `.py`) code under python/ctsm. Other CTSM python codes are following the same rationale too, so it became our new standard.

> I was also wondering if it's possible to make [DEFAULT_FILE](https://github.com/ESCOMP/CTSM/blob/master/python/ctsm/subset_data.py#L78) configurable via args so we can overwrite it for other machines?

The default configuration files are intended to be used besides command line arguments. The default configuration files can be modified to point to files you want for different machines and the command line arguments are for changing the fields based on the user choices (for example `--dompft`). Here in the CTSM python codes we use config (namelist files) to point to files.

You can find the python design/standard standard under [doc/design/python_script_user_interface.rst](https://github.com/ESCOMP/CTSM/pull/1598/files#diff-c76831da4582bbe9aad6e98d00a0082045b07d65616576be075b60430d8ae6fa)


If this answers your questions I can go ahead and closet this issue.

**Comment by ka7eh** [comment]
Thanks for the clarification, @negin513. It makes sense now. And thanks for sharing the design docs. I'll check them out later to get familiar with the dev recommendations and practices. I'll close the issue.
