### ISSUE TITLE
Subset data should allow setting to 100% vegetated AND pull the PFTs from the surface file

### ISSUE THREAD

**Issue by adrifoster** [ESCOMP/CTSM#1707]
### Brief summary of bug

The way subset data currently functions is incorrect, I believe. Right now, you must either pick:

 1) dominant pft(s)    or 
2) --include-nonveg (overrides default setting non-veg units to 0%)

I don't think this should be the way it functions because I believe there are many users (e.g. FATES users) who would not want to set a dominant pft(s) and would also want all 100% vegetated at the single point.

Note: I realize that FATES (currently) does not actually use the surface data to specify PFTs, but I still think it is confusing and incorrect to set one or multiple dominant PFTs when we don't actually want one.

### General bug information

**CTSM version you are using:** ctsm5.1.dev090

**Does this bug cause significantly incorrect results in the model's science?** [No]

**Configurations affected:** [N/A]

### Details of bug

[This](https://github.com/ESCOMP/CTSM/blob/449345ee9a534316cba0d6b4fd696b8d57e60428/python/ctsm/site_and_regional/single_point_case.py#L215) function checks to make sure one of the above arguments is set, which I don't think should be the case.

Users should be able to set the landunit to 100% vegetated AND use the default PFTs/percentages that are in the surface file.

**Comment by negin513** [comment]
Thanks for creating this. This feature was explicitly requested by the reviewers, but I agree with you that it should be disabled if it does not make sense for FATES users. 

As you pointed out, `check_nonveg` explicitly checks for at least one of `--dompft ` or  `--include-nonveg` is chosen by the user . At first, I thought this would be the only modification needed.

However, this is slightly more because there is a  `dompft` needed if we want to zero out non-vegetation land units.

This is where we will have issues:
https://github.com/ESCOMP/CTSM/blob/449345ee9a534316cba0d6b4fd696b8d57e60428/python/ctsm/site_and_regional/single_point_case.py#L425-L440

There are two ways to avoid this:
1. My original suggestion to avoid this was using a default `dompft`, but I remember there were some  issues against using a default pft.

2. Adding another ifs to check if dom_pft exists as #1727:
``` python
            if self.dom_pft is not None:
                max_dom_pft = max(self.dom_pft)
                if max_dom_pft < NAT_PFT:
                    f_mod["PCT_NATVEG"][:, :] = 100 
                    f_mod["PCT_CROP"][:, :] = 0 
                else:
                    f_mod["PCT_NATVEG"][:, :] = 0 
                    f_mod["PCT_CROP"][:, :] = 100
``` 

@ekluzek @adrifoster can you please check to see if this makes sense? With the changes proposed in #1727, when the user does not set a dompft, we will not change `PCT_NATVEG` and `PCT_CROP` but we are zero-ing out `PCT_LAKE`, `PCT_WETLAND` , `PCT_URBAN` , and ` PCT_GLACIER`. Wouldn't that be problematic? I am afraid now the sum of PCT land covers do not add up to 100.

**Comment by adrifoster** [comment]
@negin513 I think your second option is the way to go. My opinion is that the default behavior should be to:

1. Zero out non-veg units (which the script currently does)
2. Not change any of the pft percentages/presences on the surface dataset

If the user *does* want to change the `dompft`(s) and percentages I think they should be required to provide those metrics.  This eliminates the need for a default `dompft`, since it is just going to be whatever is on the surface dataset. And it avoids the user accidentally changing the PFT percentages because they must be explicit if they want to change things.

As for the problem with `PCT_NATVEG` and `PCT_CROP`: 

Could you grab the current percentages of those values and then re-calculate the new percentage? (e.g. if we have 30% nat veg and 10% crop, the *new* zero-nonveg percentages would be 30/(30 +10) for nat veg and 10/(30 + 10) for crop

**Comment by negin513** [comment]
I agree and I liked the idea of recalculating remaining percentages so they add up to 100%. I have already implemented it. :grin:

**Comment by adrifoster** [comment]
@ekluzek I think @negin513 may have already implemented this requested change?

**Comment by ekluzek** [comment]
Yes, this looks like it functions the way we need now.
