### ISSUE TITLE
Why CropPhase()?

### ISSUE THREAD

**Issue by samsrabin** [ESCOMP/CTSM#1772]
@billsacks , 

I notice you added a subroutine `CropPhase()` to check the status of an array of patches. This is called in various allocation functions. Is there a reason you chose to do this instead of directly querying the `cphase_patch` variable in `crop_inst`?

**Comment by billsacks** [comment]
Good question @samsrabin. Thanks for opening this discussion issue to record the discussion for others who may be interested, and sorry for the delayed reply (I was on vacation the last two weeks).

At first I was hoping I could just use cphase_patch, but I was concerned about driver ordering issues. These are complicated by the fact that CropPhenology is called *before* the use of crop phase in the NutrientCompetition code when using FUN, but *after* the NutrientCompetition code when not using FUN. I further noticed that some of the variables that determine crop phase (e.g., gddtsoi) are updated in places that are significantly separated from the call to CropPhenology. Taken together, I felt that using the existing cphase_patch would risk changing answers (which was a short-term issue for my development) and introducing possibly undesirable interdependencies in driver ordering (a possible long-term issue). So I went with what felt like a safer approach of maintaining the current logic, but just removing code duplication.

That said, I can certainly see some argument for using cphase_patch here. It might warrant some more analysis to determine if that's really a correct and safe change to make - but if you already have developed a sense for this, or would like to dig into it more, then I think it could be a fine (and in some ways better!) solution.

**Comment by samsrabin** [comment]
Ahh, okay, that makes a lot of sense, thanks! I think I might end up at some point writing a helper function to be used in both CropPhenology() and CropPhase() that determines what phase a single patch should be, just to further minimize the duplication. If I do, I'll refer back to this issue.

And no worries about the delayed reply, I figured it was a vacation and it wasn't urgent anyway.

**Comment by billsacks** [comment]
> I think I might end up at some point writing a helper function to be used in both CropPhenology() and CropPhase() that determines what phase a single patch should be, just to further minimize the duplication.

Sounds great – that could be a good additional step. (My original intent was to do that, but as mentioned in some comments that I added around the relevant code, it was trickier than I had hoped because of what appeared to be intentional minor differences between those two places. The context that led me to introduce CropPhase was wanting to consolidate some duplication in the nutrient competition code; consolidating the duplication between that and CropPhenology was somewhat tangential to that effort, which is part of why I didn't spend the time going further. I bring that up just to help with some context for why this is the way it currently is.)
