### ISSUE TITLE
Remove the non-working options in run_neon

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#1906]
There are a couple of non working options in the run_neon script that we should remove until they can be implemented and tested to work.

--start-date
--end-date
--run-type sasu (until SASU comes to CTSM main)

WRW is also adding: 
- [x] create a unit test for run_neon.py to the definition of done for this item, as such I'll close #1441, which is now duplicated.
- [ ] Remove the above argument options
- [x] Remove diff_month

**Comment by ekluzek** [comment]
We should also make sure the --rerun, --run-from-postad,  and --no-batch options are functional and work correctly. Also does --end-date and --run-length provided together work? It probably should abort with an error if both are provided.

@TeaganKing and @wwieder and I talked about this some yesterday.

**Comment by ekluzek** [comment]
Also diff_month can be removed as it's not used. And the end-date option can be removed as well.

**Comment by ekluzek** [comment]
@TeaganKing took care of most of this in her PR. The one thing left to do is to remove SASU for run_type.

**Comment by TeaganKing** [comment]
SASU actually has been removed already as a valid run type in `arg_parse`. See [here](https://github.com/ESCOMP/CTSM/blob/master/python/ctsm/site_and_regional/neon_arg_parse.py#L124). I left the option commented out so that we can easily add it back in once SASU comes into main (although I am unaware of the details/timing on this, so let me know if there's a better alternative).

So, I think we can close this issue, as long as #1926 addresses all of the other concerns raised in this issue?

**Comment by ekluzek** [comment]
Awesome. Thanks @TeaganKing. Leaving it commented out is fine, since it will come back with CN-Matrix. That will still be a while though, likely after LMWG.

Yes, I will close this now! Which feels good to do!
