### ISSUE TITLE
Add --silent option to ctsm_logging python infrastructure

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#1941]
I'd like to add a "--silent" option to ctsm_logging for our python scripts. This would allow an additional logging level that would suppress warnings, but still abort on error.

The reason this would be helpful is that subset_data writes out a warning if the --dom-pft option is used and for #1812 I'd like the warning to not show up.

**Comment by ekluzek** [comment]
This is simple to do:

``` python
index ff51c6d8f..9768fed5f 100644
--- a/python/ctsm/ctsm_logging.py
+++ b/python/ctsm/ctsm_logging.py
@@ -68,6 +68,9 @@ def add_logging_args(parser):
     logging_level.add_argument(
         "-v", "--verbose", action="store_true", help="Output extra logging info"
     )
+    logging_level.add_argument(
+        "-s", "--silent", action="store_true", help="Only output errors"
+    )
 
     logging_level.add_argument(
         "--debug",
@@ -84,6 +87,8 @@ def process_logging_args(args):
         root_logger.setLevel(logging.DEBUG)
     elif args.verbose:
         root_logger.setLevel(logging.INFO)
+    elif args.silent:
+        root_logger.setLevel(logging.ERROR)
     else:
         root_logger.setLevel(logging.WARNING)
 

```

**Comment by ekluzek** [comment]
Additional error checking could be done to ensure that you don't try to turn more than one of verbose, silent, or debug at once.

**Comment by ekluzek** [comment]
And the doc/design/python_script_user_interface.rst should be updated.

**Comment by billsacks** [comment]
Sounds good. There should already be error-checking in place to ensure that only one logging option is chosen, via the use of a mutually-exclusive group:

https://github.com/ESCOMP/CTSM/blob/c155ccbc61be41d75b35f0b58c3ade0a51af1c05/python/ctsm/ctsm_logging.py#L66

One thing I'd change from your proposed solution is that I don't think we should allow the short `-s` option: we should just have `--silent` – otherwise we can't use `-s` for any other purpose in any of our scripts (and there may already be some uses of that).
