### ISSUE TITLE
Update units for area to radians^2 in surface datasets to be compatible with ESMF

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#1964]
The units on surface datasets is currently km^2. We should change that to radians^2 as that's the unit that's needed on ESMF mesh files. We have a conversion process for surface datasets to mesh files and we need the radians^2 unit on them for this to work.

**Comment by billsacks** [comment]
Comment from today's ctsm-software meeting (from @samsrabin ) - either keep area as km2 as a different field, or at least have metadata saying how to convert from one to the other.

**Comment by billsacks** [comment]
@ekluzek - reading through the relevant ESMF support thread, it's not clear to me that this is really needed: @oehmke mentioned in that thread:

>  That being said, the only time we use this for calculation is if user areas are used during conservative weight calculation (e.g. with the —user_areas flag in ESMF_RegridWeightGen), so if you aren’t doing that, it won’t affect the calculation, even then if both sides are using the km^2 unit then it should still work.

So unless we are using `--user_areas` or the equivalent option in the runtime calls, it seems like we could keep areas as km^2 since that is more useful for users.

**Comment by ekluzek** [comment]
It turns out area actually isn't being read in currently from the mesh files in CESM, so there is no reason to go forward with this especially since km^2 is known to be useful to people.
