### ISSUE TITLE
Make an interface to add history fields of arbitrary type

### ISSUE THREAD

**Issue by samsrabin** [ESCOMP/CTSM#1981]
As part of #1863, @billsacks [suggested](https://github.com/ESCOMP/CTSM/pull/1863#discussion_r1002715597) that there are some values I'm saving as reals that should actually be integers. Indeed, some existing variables would best be converted to integers—e.g., `cphase_patch`, `sdates_thisyr`, and `hdates_thisyr`. However, as far as I can tell, `hist_addfld1d()` and `hist_addfld2d()` are only capable of saving reals—I got type errors when I tried to compile the code with my new variables as integers.

It seems like this could be worked around with an interface similar to what's done for `restartvar()`:
```fortran
  interface restartvar
     ! DIMS 2 refers to variables with degenerate second dimension, i.e. with
     ! size(second dimension) = 1. For variables with non-degenerate second
     ! dimension, call restartvar_2d_{TYPE}_bounds.
     !DIMS 0,1,2
     !TYPE text,int,double
     module procedure restartvar_{DIMS}d_{TYPE}
     !TYPE int,double
     module procedure restartvar_2d_{TYPE}_bounds
  end interface restartvar
```

In addition to adding type flexibility, we could even get rid of the separate 1d and 2d versions to make just a single `hist_addfld()` interface.

Having never made an interface before, this seems somewhat simple to do, but I might be missing something.

**Comment by billsacks** [comment]
My mistake – I guess all the integer fields we have on history files are added with some other mechanism... glancing at them now, it looks like they are non-time-varying fields, so that makes sense. Sorry for misleading you here.

As for your suggestion: I agree that it could make sense to do this, but it would be more involved than your suggestion: In addition to adding the interface, we would also need separate implementations for each version. This may be possible using the same techniques as are used for restartvar, which leverages genf90, though it may become somewhat involved depending on how much needs to change between the different versions. One key difference between history and restart variables is that we store pointers to each history variable in an array of history field structures... that piece would need to be generalized to handle ints as well as reals. So, while I agree that this is a good idea, I think it would take some effort, so we probably should defer this.

**Comment by samsrabin** [comment]
Ah okay, makes sense. Thanks!

**Comment by samsrabin** [comment]
In addition to the above, Bill pointed out that special handling would be required to deal with potential spatial and temporal averaging (or to prevent these variables from being averaged). It seems like this would be much more effort than it's worth for now, so I'm closing this as wontfix.

**Comment by samsrabin** [comment]
As pointed out by @ekluzek, [this method](https://github.com/ESCOMP/mizuRoute/blob/e165e13d7b07aca5b3936fe91c5576f49ad452c6/route/build/src/pio_utils.f90#L535) that @nmizukami used for MizuRoute could be easier than the interface method.
