### ISSUE TITLE
Add prh30 to params file for fire tuning

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/CTSM#206]
_From @ekluzek on May 23, 2017 17:57_

Fang would like a new constant for tuning the CLM50 fire model. This constant only applies to Li2016 model and not the older version. So this acts a little bit different than other constants which are shared between both. So we may need to add a namelist read to just the newer version.

Here's the email from Fang which defines what to do...

Hi Dave and Erik,

     It would be better if Erik could help change (in CNFireLi2016Mod.F90)

arh30=1._r8-max(0.7_r8, min(1._r8,rh30_col(c)/90._r8))

to

arh30=1._r8-max(prh30, min(1._r8,rh30_col(c)/90._r8)) and define prh30=0.7_r8

In this way, we could tune the parameter (prh30) by just changing user_nl_clm if necessary, like ufuel...

    Dave, low burned area in tropical deciduous tree region (casued by very high BTRAN2 and fuel load in r229) could be solved better if I set prh30 to 0._r8 or 0.4_r8, but I'm not sure it's performance in coupling case, CLM5's later version, or newer forcing data, so I didn't suggest change in prh30 value this time.

Thanks,

Fang

_Copied from original issue: NCAR/CLM#8_

**Comment by ekluzek** [comment]
This will be moved to the params file for Li2016 in the hardcodedp branch coming to master.

**Comment by ekluzek** [comment]
We are adding this on as a parameter on the paramsfile NetCDF file. I think the way that makes the most sense with this is to add the read for the parameter to the Li Fire base class, so that it will be read regardless of which Lit File Model is being used, and could be use for any future version as well. This would also be true for future fire variables that could be added in for the Li fire model series.
