### ISSUE TITLE
Improve ChangeLog template

### ISSUE THREAD

**Issue by samsrabin** [ESCOMP/CTSM#2070]
At [today's CTSM software engineering meeting](https://docs.google.com/document/d/1Qn9c7NiGxYMN3p47Fpa0QINLwwxzRpGXG61GsuGjVM0/edit#heading=h.uqq9xqk1nav), we discussed a few parts of the ChangeLog template that need updating (or at least reconsideration):
- There seemed to be unanimous agreement for removing the "Known bugs found since the previous tag" section, since Github Issues now serves this function.
- There could be better instructions for how to determine whether answer changes are roundoff-level, larger than roundoff but same climate, or climate-changing.

The latter will likely require more discussion. Some notes:
- There seemed to be agreement that the "roundoff or larger" distinction can be determined by how large the differences are _at the line(s) in question_. So, e.g., differences that arise because of order-of-operations changes are roundoff-level, even if they propagate to larger changes.
- We didn't discuss what it means for a change to be climate-changing.
- We might want to have these instructions on the wiki or in a different repo file, rather than in the ChangeLog template itself.

**Comment by ekluzek** [comment]
In terms of simplification I wonder about removing these two in the ChangeLog?

```
Externals issues fixed (include issue #):

List any externals directories updated (cime, rtm, mosart, cism, fates, etc.):
```

The first one is often hard to actually figure out, but might be useful to have in the ChangeLog -- because it takes work to figure this out using github?

The second just repeats what you did in the Externals* files, so maybe isn't helpful.

As I said in the past I found the ChangeLog to be really critically useful, so I'm a little reluctant to let it go. But, I also see that github is working so much better, so it may not be as useful as it was in the past. Also note that we don't have a ChangeLog for neither SLIM nor mizuRoute, and that seems to be fine.

Also we did agree that you can remove a section that you don't do any reporting on. We should make sure everyone is clear on that...

**Comment by samsrabin** [comment]
Good points, Erik. The "Externals issues fixed" one would probably require a fair amount of work on our part to look at each external repo's commits between the old and new version. Perhaps we could ask that to be filled out _if_ there's a specific problem in our runs that an external is being updated to resolve.

I like having the "List any externals updated" section for the same reason I like ChangeLog itself: it's more easily searched than Github or `git log`.

And yes, I like that we can remove any section that doesn't apply to our commit. The ChangeLog template is good about repeating that for pretty much every section, so hopefully it is clear enough.

**Comment by billsacks** [comment]
> The "Externals issues fixed" one would probably require a fair amount of work on our part to look at each external repo's commits between the old and new version. Perhaps we could ask that to be filled out _if_ there's a specific problem in our runs that an external is being updated to resolve.

I personally use it in exactly that way: If I'm doing an externals update explicitly to fix some externals issue, then I list it there, otherwise I generally (always?) don't bother putting anything there. So I'd suggest that, if we keep it, we agree to focus it on that usage.

Whether to keep that and the "list any externals updated" I think depends on how useful they are to people reading the ChangeLog: at least with the above suggestion, they don't take too long to write, so I'm okay keeping them if they're useful.
