### ISSUE TITLE
Rename MIMICS History Fields

### ISSUE THREAD

**Issue by wwieder** [ESCOMP/CTSM#2095]
MIMICS history fields should be renamed to make them easier to find.  For example [litter pools are currently written](https://github.com/ESCOMP/CTSM/blob/942de5c248d891cbde945a2c8c27a01af697bc86/src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90#L484) as:
`MET_LIT` & `STR_LIT`, which makes them hard to find on history files.

Seems like naming them `LIT_MET` `LIT_STR` on history files may make more sense?  What do you think of this suggestion @slevis-lmwg ?

**Comment by slevis-lmwg** [comment]
Created branch `rename_mimics_hist_flds` and
        modified:   cime_config/usermods_dirs/newton_krylov_spinup/user_nl_clm
        modified:   cime_config/usermods_dirs/output_bgc/user_nl_clm
        modified:   src/soilbiogeochem/SoilBiogeochemDecompCascadeBGCMod.F90
        modified:   src/soilbiogeochem/SoilBiogeochemDecompCascadeMIMICSMod.F90
and submitted the cheyenne test-suite.

**Comment by slevis-lmwg** [comment]
@wwieder I have encountered a dilemma for which I would like feedback:

In several modules (eg, CNVeg[Carbon,Nitrogen]FluxType and SoilBiogeochem[Carbon,Nitrogen][Flux,State]Type) we construct history field names at run-time by appending C or N or variations of such strings at the end. Combined with my naïve code mods that replace MET_LIT with LIT_MET (and so on for the others), I end up with LIT_METC (for what used to be MET_LITC). At first glance:
- I don't like attaching C and N to the MET rather than the LIT, but maybe you don't mind and can convince me that it's fine
- I don't want to complicate the code by requiring C and N in the middle of LIT_MET

So I have alternative suggestions:
1) Simple: Separate the C/N with an underscore to make LIT_MET_C. This way, little else has to change, as far as I can tell.
2) Complicated: Append the C and N to the beginning rather than the end to make C_LIT_MET. If so, we are faced with widespread changes throughout the model because we consistently attach the C/N to the end of field names.

For now I will start with (1) and we can decide later.

**Comment by wwieder** [comment]
I'm fine with your suggestion to use LIT_MET_C
