### ISSUE TITLE
CPLHIST case is matching the wrong CLM_NML_USE_CASE

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/ctsm#213]
@olyson found that a CPLHIST spinup case he setup with clm4_5_18_r270 improperly sets CLM_NML_USE_CASE=20thC_transient. The reason for that is config_componen.xml matches "HIST" as follows...

      <value compset="1850.*_"          >1850_control</value>
      <value compset="HIST.*_"          >20thC_transient</value>

Since the match doesn't say which part of the string should be matched, Keith's case with a long compset name of:

1850_DATM%CPLHIST_CLM50%BGC-CROP_SICE_SOCN_MOSART_CISM2%NOEVOLVE_SWAV

matches the HIST pattern above, and uses it, rather than the first one with 1850.

So these patterns should have better matching going on.

Currently for testing the only spinup compset we have is: 

 ```
   <alias>I1850Clm50BgcSpinup</alias>
    <lname>1850_DATM%S1850_CLM50%BGC_SICE_SOCN_MOSART_CISM2%NOEVOLVE_SWAV</lname>
```

So we need to look into also covering a CPLHIST case, or switching over to it.

**Comment by ekluzek** [comment]
It turns out we have no tests with the I1850Clm50BgcSpinup and that compset can't function because %S1850 isn't an option anymore in cime. And even updating that to CPLHIST doesn't allow it to work, since datm in cime is no longer setup to properly take care of it, like it used to be. So this is a bigger issue than I originally thought.

**Comment by ekluzek** [comment]
Keith's case is here:

/glade/p/work/oleson/clm4_5_18_r270/cime/scripts/clm50_r270_1deg_CPLHSTTest_1850

Some important settings:

	DATM_CPLHIST_CASE: b.e20.B1850.f09_g17.pi_control.all.221.cplhist
	DATM_CPLHIST_DIR: /glade/p/cesm/bgcwg_dev/forcing/b.e20.B1850.f09_g17.pi_control.all.221.cplhist/cpl/hist.mon
	DATM_CPLHIST_YR_ALIGN: 1
	DATM_CPLHIST_YR_END: 118
	DATM_CPLHIST_YR_START: 99

prescribed aerosols were pointed to by hand.

**Comment by ekluzek** [comment]
CPLHIST spinup cases stopped being tested in the testlist/compset upgrade in clm4_5_16_r249.

**Comment by klindsay28** [comment]
The Feb 15 comment on Keith Oleson's case refers to cplhist output in the directory
/glade/p/cesm/bgcwg_dev/forcing/b.e20.B1850.f09_g17.pi_control.all.221.cplhist/cpl/hist.mon
I created this output for the purpose of 'kicking the tires' on cplhist configuration. I am not intending this output to be available indefinitely, as it is based on output from a development version of CESM2.

Because this output is not from the final version of CESM2, I have been reluctant to place a segment of this model output in the inputdata repository. I've been concerned that others might think that output in the inputdata repo is official in some sense, and I wouldn't want people to think that of output from a development version of CESM2.

That said, I've been concerned that cplhist compsets for POP are not being tested, as @ekluzek  appears to be for I1850Clm50BgcSpinup compsets. It's a bit of conundrom. As far as I can tell, testing on platforms beyond cheyenne basically requires inputdata datasets, but I'm reluctant to commit to that with output from development versions of the code.

My plan has been to introduce such a test once I can generate output from the 'physics frozen' version of CESM2 and have that put in the inputdata repository (perhaps just 1 year). I think CTSM could use the same forcing in its cplhist testing.

How does that sound to you @ekluzek ?

**Comment by ekluzek** [comment]
@klindsay28 yes, that sounds good. I agree with your analysis, to really do this we need to have datasets in inputdata -- but, I understand your reluctance to install preliminary data. 

Although you should also consider that we are always finding bugs and moving to the next version of the model, and "physics frozen" seems like an elusive target. 

For CTSM, we need more than a year, in case you have a drought at a point for an entire year. At least a few years is advisable. And yes I would hope we can use the same set of data. I did add some testing on cheyenne for the preliminary data that Keith was using.
