### ISSUE TITLE
leafcn for pfts 15 and 16 have diverged, should probably be the same

### ISSUE THREAD

**Issue by slevis-lmwg** [ESCOMP/CTSM#2184]
### Brief summary of bug

A user posted in the CESM Forums that pfts 15 and 16 have different leafcn in the params file. 

Here is what I found going back in time:
clm5_params.c170303.nc: 28.0269058295964, 25  ! we have used these values since this file
clm5_params.c170202.nc: 28.0898876404494, 25  ! these values appeared temporarily
clm5_params.c161105.nc: 31.9110426104045, 25  ! these values appeared temporarily
clm5_params.c161103.nc: 25 25  ! last file with these values

### General bug information

**Does this bug cause significantly incorrect results in the model's science?**
Possibly (see next).

**Configurations affected:** 
In simulations with no irrigation, pft 16 (irrigated generic crop) merges with pft 15 (unirrigated generic crop). So any pft 16 area will have leafcn = 25 in simulations with active irrigation, and the other value in simulations with inactive irrigation.

**Comment by wwieder** [comment]
I suspect this bug goes back to the frantic CLM5 calibration efforts and suggest we make these the same.
- Aren't these values going to used for simulations with explicit crop management too?  
- Since all the other crop C:N ratios are integers, I suggest we move this back to 25 for PFT 15. 
- Can we do an i2000 simulation to evaluate the impact of this bug on crop yields (in a crop case) and GPP / LAI (in a BGC case).  These may require spinup?

How carefully do we need to evaluate these kinds of bug fixes?  Maybe this can get brought in with another answer changing bug-fix tag?

**Comment by slevis-lmwg** [comment]
This issue is linked to the "upcoming tags" [card](https://github.com/ESCOMP/CTSM/projects/6#card-90758934) that handles answer-changing params file changes.

**Comment by wwieder** [comment]
Should we add the FUN bug #2120 to this answer-changing param file change too?

**Comment by slevis-lmwg** [comment]
I vote YES :-)
