### ISSUE TITLE
Sys test requirements for mksurfdata_esmf

### ISSUE THREAD

**Issue by slevis-lmwg** [ESCOMP/CTSM#2228]
1) mksurfdata_esmf uses MPI, so good to add a system test for changing PE layouts:
- Add the test to aux_clm or to pymods?
- Compare the generated fsurdat files and expect bit-for-bit.
2) The test could go on to check that the CLM runs with the generated fsurdat file.

**Comment by wwieder** [comment]
Testing is always important, but is this critical to happen before we merge CTSM5.2 to main? 

I guess my question is how much of a blocker is the before we can make a CTSM5.2 tag?

**Comment by ekluzek** [comment]
@wwieder these are good questions. We need to keep in mind the reasons for testing, and that is to find problems as soon as possible so they are easy to fix. The more time that happens between testing -- the more likely the changes are bigger and harder to identify the problem. And debugging is both unpredictable and expensive with both being bad. So it might take days to weeks to a month to fix a problem.

The thing is mksurfdata_esmf is heavily integrated into the system as well as being more complex than mksurfdata_map. It's closely dependent on external updates for example. And without regularly testing it an external update might break it. Especially, since it might not be tested with the external that gets updated. Which reminds me that we should add at least one of these tests to at least the CESM prebeta test as that we identify issues when externals are updated in CESM tags.

So it's critical that we have some testing here. Otherwise we'll make the CTSM5.2 tag and then have it broken in future tags until we do the testing again.

Now, we can also add some testing and plan on increasing it with time. But, yes I consider it a blocker in order to save time down the line. Or at least potentially save time, with the probably of that being high enough that we need to get something in place here.

And I can say that we have a good start at this, so we might be pretty close to what's needed here. And then we can add more testing with time after ctsm5.2.0 is made. But, always good to ask these sorts of questions -- what can we shave off in terms of what needs to be done?

**Comment by ekluzek** [comment]
This will close with ctsm5.2. The question is asked here if the testing we have there is sufficient. But, we do have some, and let's wait until we see a problem with the testing.
