### ISSUE TITLE
Optimize PE layouts for Derecho

### ISSUE THREAD

**Issue by samsrabin** [ESCOMP/CTSM#2244]
Waiting on #1995, where some initial PE layouts will be implemented.

**Comment by ekluzek** [comment]
For this we should optimize PE layouts for important grids. Here's my initial cut at that list:

f09
f19
ne30np4.pg3
hcru
nldas2
f45
f10
C96
mpasa120

We might need to optimize for high and ultra-high resolutions grids if that's important for CAM and groups working on these resolutions (if they are going to simulations with standalone CLM).

**Comment by ekluzek** [comment]
There's also "S" PE layouts for f09 and f19 as well as nldas2 and those should be optimized as well.

We currently also have PE layouts for: f05, f02, ne240, C384, C192,  and T31 that we can drop.

And there are specific PE layouts for the following (from grep on the config_pes.xml file). We should check if all of these should be supported as well @adamrher?...)

``` XML 
  <grid name="l%ne0np4CONUS" >
  <grid name="l%ne0np4CONUS" >
  <grid name="l%ne0np4.ARCTICGRIS.ne30" >
  <grid name="l%ne0np4.ARCTICGRIS.ne30" >
  <grid name="l%ne0np4.ARCTIC.ne30" >
  <grid name="l%ne0np4.ARCTIC.ne30" >
  <grid name="l%ne120">
```

**Comment by ekluzek** [comment]
In #1967 here https://github.com/ESCOMP/CTSM/pull/1967#issuecomment-1974121803

I found that the PE layouts for a lot of resolutions just use one node, and if memory increases just a bit, that tests can fail because not enough processors are used. So it would be good to increase the PE layout size for the resolutions I discovered problems with there.

**Comment by wwieder** [comment]
also closing this issue (for now)
