### ISSUE TITLE
Growing rainfed and irrigated rice in different seasons using planting window parameters

### ISSUE THREAD

**Issue by KNR8070** [ESCOMP/CTSM#2398]
CLM in its current state throws error while trying to simulate rainfed and irrigated rice in different seasons. I tried to prescribe different planting windows to 61 and 62 cfts in clm_param file. 

@samsrabin

**Comment by samsrabin** [comment]
Thanks for filing this, Narender. If you're running on an NCAR system, could you give me the path of the case directory so I can investigate? If not, could you paste in the error message here?

**Comment by KNR8070** [comment]
No, I am not running on NCAR. 
I wanted to confirm the error with some new simulations. 

- With the bug fix in tag ctsm5.1.dev131 (i.e. fixing the sowing of crop in the same year it is harvested), land model now simulates two seasons of rice in a year. 

I am currently putting together two new simulations: the default land model (without bug fix) and with modifications, to test if the bug pops up.

I'll update you once the simulations are complete.

**Comment by KNR8070** [comment]
Hi, 
Initial simulations are completed. A simple plot of rice lai over the period 2000 to 2014 in two sets of experiments- Default, and Modified.
The Default case is devoid of bug fix of ctsm5.1.dev131, while Modified case has this bug fixed. And the results look like this.
![Rice_inTwoSeasons](https://github.com/ESCOMP/CTSM/assets/67633997/aa64223b-9de4-45ff-a2b7-5961bd8c2742)

We can find an undesirable and unpredictable nature of rice growing in the default case and that is rectified in the modified case

**Comment by KNR8070** [comment]
Things to note:
1) If we are growing rice in rabi season (Oct-Mar), then the planting temperatures used in the kharif season would not work. And therefore, planting is occurring on the last day of the planting window (Nov-01 to Dec 31).
2) Since the crops are growing in two distinct weather conditions, the crop parameters should also be different, considering different crop varieties are sown in these two seasons.

**Comment by samsrabin** [comment]
So if I'm understanding this correctly, it looks like it _is_ possible to have different sowing windows for rainfed vs. irrigated, right? That's good if true, in which case we can close this issue. The remaining problem would be that the rabi season rice needs to be reparameterized separately from the kharif season rice.

**Comment by KNR8070** [comment]
Yes, that's right. With the capabilities of crop growing in two years in CLM5, we can now grow rainfed and irrigated rice in different seasons. The parametrization of irrigated rice needs to be checked. One more thing we need to be mindful of is the area of rainfed and irrigated crops. Does it represent the actual kharif and rabi crops?

**Comment by samsrabin** [comment]
Okay, great! I'll close this issue.

That's a good question about whether the area in the default land use datasets represents the actual kharif and rabi areas. The short answer is: maybe! The crop areas are constructed based on a combination of LUH2 data (which doesn't give "rice" but rather "C3 annual") and FAO data. I can't give you a definitive answer because I don't have better area data, especially when you get down to the level of seasonality. Examining this would be a great addition to the Discussion section of your current manuscript.

By the way, it would be possible to make a land use dataset that runs both irrigated and rainfed rice in every gridcell. This would allow you to then apply any crop area dataset in postprocessing. If you're interested in this, send me an email and I'll walk you through it.
