### ISSUE TITLE
NEON case won't build: redundant usermod information

### ISSUE THREAD

**Issue by wwieder** [ESCOMP/CTSM#2470]
### General bug information
NEON case created from scratch failed to build in derecho 
```
ERROR: in validate_variable_value (package Build::Namelist): Variable name fsurdat has exceeded the dimension size of the array.
```
FWIW, here's the fsurdat file
```
fsurdat = "$DIN_LOC_ROOT/lnd/clm2/surfdata_map/NEON/surfdata_1x1_NEON_${NEONSITE}_[hist_78pfts_CMIP6_simyr2000_c230601.nc](http://hist_78pfts_cmip6_simyr2000_c230601.nc/)"
```

**CTSM version you are using:** [output of `git describe`]
ctsm5.1.dev176

**Does this bug cause significantly incorrect results in the model's science?** [Yes / No]
no

**Configurations affected:** 
NEON case created from scratch

### Details of bug
```
./create_newcase --case /glade/derecho/scratch/wwieder/neon_tests/HARV.ad --res CLM_USRDAT --compset I1PtClm51Bgc --output-root /glade/derecho/scratch/wwieder/neon_tests --run-unsupported --user-mods-dir NEON/HARV
```

It seems removing these lines solves the issue
```
flanduse_timeseries = ' '   ! This isn't needed for a non transient case, but will be once we start using transient compsets
fsurdat = "$DIN_LOC_ROOT/lnd/clm2/surfdata_map/NEON/surfdata_1x1_NEON_${NEONSITE}_hist_78pfts_CMIP6_simyr2000_c230601.nc"
```
I'll plan to submit a PR to b4b-dev.

**Comment by ekluzek** [comment]
I've tried to reproduce this and can't seem to get it to fail for me. I also tried to using bash, and sourcing @wwieder bash startup files. So I'm stumped as to why this isn't working for him.  The error also doesn't make sense in this context because it's as if fsurdat in the user_nl_clm is arrayed valued. If it was

`fsurdat(1) = "$DIN_LOC_ROOT/lnd/clm2/surfdata_map/NEON/surfdata_1x1_NEON_${NEONSITE}_hist_78pfts_CMIP6_simyr2000_c230601.nc"`

it would explain it, but it's not.

I'm also not seeing that the perl version makes a difference here.

**Comment by wwieder** [comment]
I also started clean (again) was was not able to recreate the error.   At the same time, the lines from user_nl_clm removed from usermods_dirs in #2472 are redundant, so I suggest we just keep them in
