### ISSUE TITLE
Move Smallville data to ...clm2/testdata/

### ISSUE THREAD

**Issue by samsrabin** [ESCOMP/CTSM#2515]
As [discussed](https://docs.google.com/document/d/1tgDRocjAFF1svWjt0mvjjPaPLFuDZEHLpf4vlGIQs5o/edit#heading=h.f6fgfzwuk999) in CTSM SE meeting today, this makes it clear that [Smallville](https://en.wikipedia.org/wiki/Smallville_(comics)) is a fake site we made up for testing purposes.

**Comment by ekluzek** [comment]
Also do this for the 1x1_cidadinhoBR site.

**Comment by ekluzek** [comment]
@slevis-lmwg and I started discussing this in the context of ctsm5.3.0 because we need to place the Smallville and Cidadinho surface datasets for ctsm5.3.0. We are thinking that having them under the surfdata_esmf location, but also under a "synthetic" directory to point out they are synthetic datasets to be used for testing might be helpful. The expectation has been that ALL surface datasets are under a surfdata directory, so finding them elsewhere isn't obvious.

So one suggestion would be a directory structure like this:

lnd/clm2/surfdata_esmf/ctsm5.3.0/synthetic

or it could be:

lnd/clm2/surfdata_esmf/synthetic/ctsm5.3.0

I think I prefer the first.

**Comment by samsrabin** [comment]
That makes a lot of sense to me!

**Comment by ekluzek** [comment]
With ctsm5.3.0 smallville now resides under inputdata here:

lnd/clm2/surfdata_esmf/ctsm5.3.0/synthetic/

But, we still need to move it for:

surfdata_1x1_cidadinhoBR_hist_2000_78pfts_c240613.nc

**Comment by ekluzek** [comment]
@slevis-lmwg points out this was completed in ctsm5.3.0. I was looking for the file on Izumi rather than Derecho.
