### ISSUE TITLE
Are these checks needed anymore?

### ISSUE THREAD

**Issue by slevis-lmwg** [ESCOMP/CTSM#2569]
https://github.com/ESCOMP/CTSM/blob/6b550b1aa536fed46d197580614226e16691d1f8/bld/CLMBuildNamelist.pm#L354-L370

See this conversation thread:
https://github.com/ESCOMP/CTSM/pull/2564#discussion_r1619428681

**Comment by ekluzek** [comment]
Actually, looking at the code now, this is needed so that you get the right directory for the perl5 utilities. It's less likely to trigger with `git fleximod` as it should at least find something. But, it certainly should trigger when it can't find what it expects. This could possibly happen if directory structure or names change.

So let's close this as a wontfix. The code above looks good to me.

**Comment by slevis-lmwg** [comment]
Thanks, Erik!
