### ISSUE TITLE
Move namelist parameters to paramfile

### ISSUE THREAD

**Issue by linniahawkins** [ESCOMP/CTSM#2831]
The PPE team would like to have several parameters that are currently set in the namelist moved to the parameter file: 

Jmaxb1 (as a pft dimensioned value, per #2830)
baseflow_scalar
upplim_destruct_metamorph
maximum_leaf_wetted_fraction
interception_fraction
pot_hmn_ign_counts_alpha
decomp_depth_efolding

This is not 100% necessary for us to move forward, our scripting can handle namelist parameter modifications, but it would make things clean and simple.

**Comment by wwieder** [comment]
Thanks for opening this issue and #2830?  What's a useful timeline for these?   it may be simple enough to create the parameter file that you can use (he said naively), but then it's 2-weeks until b4b-dev comes to main.

**Comment by linniahawkins** [comment]
Neither of these are necessary for the mini-OAAT (October) nor the first latin-hypercube ensemble (November). 

#2831 would be convenient to have by November 1 (but not necessary). 
https://github.com/ESCOMP/CTSM/issues/2830 will be necessary for history matching (late November).

**Comment by olyson** [comment]
I should be able to start this soon.

**Comment by olyson** [comment]
I find that decomp_depth_efolding is already on the parameter file.

**Comment by olyson** [comment]
I think transferring **baseflow_scalar** is problematic because its value depends on the **lower_boundary_condition** chosen.  Similarly, **pot_hmn_ign_counts_alpha** is a tuning parameter for fire and depends on the fire method.
I've transferred **upplim_destruct_metamorph**, **maximum_leaf_wetted_fraction**, **interception_fraction**, and **Jmaxb1** (now **jmaxb1** and pft-dimensioned) from the namelist to the parameter file and run the following test subset with bfb results with ctsm5.3.002 (current base for b4b-dev branch).
SMS_D_Ld5.f10_f10_mg37.I2000Clm45Fates.derecho_intel.clm-FatesCold
SMS_Ld5.f10_f10_mg37.I1850Clm45BgcCrop.derecho_intel.clm-crop
ERI_D_Ld9.f10_f10_mg37.I1850Clm45Bgc.derecho_gnu.clm-default
ERP_P64x2_D_Ld5.f10_f10_mg37.I1850Clm45BgcCrop.derecho_intel.clm-crop
ERP_P64x2_D_Ld5.f10_f10_mg37.IHistClm45BgcCru.derecho_intel.clm-decStart
SMS_Ld5.f10_f10_mg37.I2000Clm50FatesRs.derecho_intel.clm-FatesCold
SMS_Ln9.ne30pg2_ne30pg2_mg17.I2000Clm50BgcCrop.derecho_intel.clm-clm50cam6LndTuningMode
ERI_D_Ld9.f10_f10_mg37.I2000Clm50BgcCru.derecho_intel.clm-default
ERP_D_P64x2_Ld3.f10_f10_mg37.I1850Clm50BgcCrop.derecho_gnu.clm-default
ERP_D_P64x2_Ld3.f10_f10_mg37.I1850Clm50BgcCrop.derecho_intel.clm-default
ERP_D_Ld5.ne30pg3_t232.IHistClm51Sp.derecho_intel.clm-default
ERI_D_Ld9.f10_f10_mg37.I1850Clm60Bgc.derecho_gnu.clm-default
ERP_D_Ld5.f10_f10_mg37.IHistClm60Sp.derecho_intel.clm-default
ERI_D_Ld9.f10_f10_mg37.I1850Clm60Bgc.derecho_gnu.clm-default
ERP_D_Ld9.ne30pg3_t232.I1850Clm60BgcCropG.derecho_intel.clm-clm60cam7LndTuningModeLDust
SMS_D.f10_f10_mg37.I2000Clm60Bgc.derecho_gnu
SMS_D.f10_f10_mg37.I2000Clm60Bgc.derecho_intel

Next, plan is to convert the parameters in https://github.com/ESCOMP/CTSM/issues/2830 (**Jmaxb0**, **wc2wjb0**, **r_mort**) to pft-dimensioned.
