### ISSUE TITLE
Add a cmip6_evolving_icesheet usermods directory

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/ctsm#345]
@lvankampenhout requests the field `ICE_MODEL_FRACTION` as annual output in cmip6 runs with an evolving ice sheet. I'll do this by adding a new usermods directory, `cmip6_evolving_icesheet` (consistent with what we already have in CISM). For now this will:

- include the cmip6 usermods directory

- have a user_nl_clm file that adds ICE_MODEL_FRACTION to the annual output stream

**Comment by billsacks** [comment]
Also, I should add a test that includes this new usermods directory. A few time steps, like SMS_D_Ln5 is sufficient: mainly need to test initialization.

**Comment by billsacks** [comment]
Also, I think I should change `ICE_MODEL_FRACTION` to be time-averaged rather than instantaneous. I think this would more often do the right thing for various history output frequencies. For example, if someone adds this to an every-10-year hist file, they'd probably want the 10-year-average ICE_MODEL_FRACTION, not the value at the end of the 10-year period.

@lvankampenhout @lofverstrom do you have any thoughts on this?

**Comment by lvankampenhout** [comment]
I support the idea of having a time-averaged `ICE_MODEL_FRACTION`. Personally , I use it to calculate area-integrated numbers, so in your example of an every-10-year hist file this makes most sense (the field being integrated is also time-averaged).

Also, right now the coupling frequency of CISM is typically one year. This means that having the output annual-averaged or instantaneous wouldn't make a difference, is that right? This would change if the coupling frequency is sub-annually, but I expect not by large margins since ice moves slowly.

**Comment by billsacks** [comment]
Thanks, @lvankampenhout . I'm pretty sure that you're right that it currently wouldn't matter if it's instantaneous or time-averaged. The thing that originally got me worried about having it instantaneous was not being completely sure whether the value written at the end of the year would apply to the current year or the previous year. I _think_ it would apply to the previous year (which I think is what you'd want), but I felt it's safer to just write the time-averaged value (where this year boundary problem would, at worst, lead to errors of 1/17520 for a 30-min time step, rather than leading to a complete year offset -- i.e., if we average just the year-boundary value into the wrong year).
