### ISSUE TITLE
Question - SSH vs HTTPS

### ISSUE THREAD

**Issue by serbinsh** [ESCOMP/ctsm#401]
This is probably a silly question, but why are we using https instead of SSH to link to repos with the externals? For example:

https://github.com/ESCOMP/ctsm/blob/07cdf9ffed29e7f83dc9aff5c5b4794105f994c5/Externals_CLM.cfg#L4

I *think* we used to use ssh but it seems to have switched to https.

**Comment by ekluzek** [comment]
@serbinsh it's really just because https is simpler/easier and doesn't require someone to do the extra steps of adding  ssh keys. I agree with you that it's a bit awkward because we recommend elsewhere to use ssh and tell you to setup ssh keys. This inconsistency is a bit confusing. But, putting ssh in externals, then requires that everyone have their ssh keys setup, which seems like too high of a standard. @billsacks do you want to comment here? Or @bertinia do you want to comment -- we do use https form for CESM as well?

**Comment by serbinsh** [comment]
OK, thanks @ekluzek I asked because suddenly when running ./manage_externals/checkout_externals I am getting requests to put in my username and password for github, which I didnt have to do before.  I tried flipping the fates external to the ssh but then it requested my ssh passphrase, which again didnt happen previously.  Not really sure where the extra layers/requests for user/pass or passphrase is coming from now?  I suppose something to do with my git account or user prefs on my cluster?  Not really sure!

**Comment by billsacks** [comment]
@serbinsh is the request for password something you're running into with ctsm master, or a branch that's pointing to (say) a private FATES repo? As @ekluzek mentioned, it's important that we use https on master (where all the dependencies are public anyway, so you should never be required to enter a password via checkout_externals), but if you have a branch pointing to a private repo, then ssh could possibly make sense.

**Comment by ekluzek** [comment]
@serbinsh as @billsacks says the reason for your being asked password, might be because you asked for NGEET/fates which is a private repo right now.

I'm going to close this issue as a won'tfix, but feel free to continue the discussion if it's helpful.
