### ISSUE TITLE
Carbon balance error in decStart test just after new year

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/ctsm#404]
In clm5.0.dev013 the following test fails

ERP_D_Ld10_P36x2.f10_f10_musgs.IHistClm50BgcCrop.cheyenne_intel.clm-ciso_decStart

The Carbon balance test fails just after the new year

```
 Get data for variable PCT_NAT_PFT for year         2002
 Get data for variable PCT_CROP for year         2002
 Get data for variable PCT_CFT for year         2002
 Get data for variable FERTNITRO_CFT for year         2002
 Get data for variable HARVEST_VH1 for year         2002
 Get data for variable HARVEST_VH2 for year         2002
 Get data for variable HARVEST_SH1 for year         2002
 Get data for variable HARVEST_SH2 for year         2002
 Get data for variable HARVEST_SH3 for year         2002
(shr_dmodel_readstrm) file ub: /glade/p/cesmdata/cseg/inputdata/lnd/clm2/ndepdata/fndep_clm_hist_simyr1849-2006_1.9x2.5_c100428.nc     155
(shr_dmodel_readstrm) file ub: /glade/p/cesmdata/cseg/inputdata/lnd/clm2/urbandata/CLM50_tbuildmax_Oleson_2016_0.9x1.25_simyr1849-2106_c160923.nc     155
 cbalance warning          29 -2.076282908826249E-004  -1074743022558.93     
 cbalance warning          33  1.643307558151647E-006  -3772871070.14197     
 cbalance warning          35  1.057602733264829E-006  -4846598290.52322     
 cbalance warning          37  3.312351869247387E-007  -4786871660.48964     
 cbalance warning          39 -1.000108391571025E-006  -4853732037.50187     
 column cbalance error    =  -1.000108391571025E-006          39
 Latdeg,Londeg=  -50.0000000000000        300.000000000000     
 begcb                    =   -4853732037.48418     
 endcb                    =   -4853732037.50187     
 delta store              =  -1.769256591796875E-002
 --- Inputs ---
 gpp                      =   9.278216705750481E-003
 --- Outputs ---
 er                       =   2.697175617008332E-002
 col_fire_closs           =   0.000000000000000E+000
 col_hrv_xsmrpool_to_atm  =   0.000000000000000E+000
 wood_harvestc            =   0.000000000000000E+000
 grainc_to_cropprodc      =   0.000000000000000E+000
 -1*som_c_leached         =  -2.656202748129549E-008
 ENDRUN:
 ERROR: ERROR in CNBalanceCheckMod.F90 at line 217
```

I also tried having it skip the carbon balance check for two time steps after the new year, and it still fails as follows...

```
 nstep =         98   TS =   269.789311867605193
 cbalance warning          29  1.547959087451964E-004  -1074743022559.03     
 cbalance warning          33  2.275679288829546E-007  -3772871070.21567     
 cbalance warning          35  1.359888517536711E-006  -4846598290.61322     
 cbalance warning          37  3.054991076101993E-007  -4786871660.51103     
 cbalance warning          39 -1.626749949537598E-006  -4853732037.57152     
 column cbalance error    =   1.547959087451964E-004          29
 Latdeg,Londeg=  -50.0000000000000        300.000000000000     
 begcb                    =   -1074743022558.98     
 endcb                    =   -1074743022559.03     
 delta store              =  -4.919433593750000E-002
 --- Inputs ---
 gpp                      =   0.000000000000000E+000
 --- Outputs ---
 er                       =   4.905428542667085E-002
 col_fire_closs           =   0.000000000000000E+000
 col_hrv_xsmrpool_to_atm  =   0.000000000000000E+000
 wood_harvestc            =   0.000000000000000E+000
 grainc_to_cropprodc      =   0.000000000000000E+000
 -1*som_c_leached         =   1.474539791604141E-005
 ENDRUN:
 ERROR: ERROR in CNBalanceCheckMod.F90 at line 217
```

**Comment by ekluzek** [comment]
And I increased the number of time-steps to skip the balance check all the way up to 15 steps and it still fails once it gets there.

**Comment by billsacks** [comment]
@ekluzek notes that this test was in the Expected Fail list before for a different reason - because crop tests couldn't run with initial conditions files with the wrong date. In the dev013 tag, he is bypassing that initial conditions date check in this test, and so now there's a failure for this reason. He suspects that this problem is specific to starting crops from an initial conditions file with the wrong date.

@dlawrenncar suggests changing this test to start from an initial conditions file at the appropriate date, since that would be more typical of what we do in practice. If it's a pain to maintain that initial conditions file, though, we could run a test for a bit over a year (with restart still happening after the year boundary, e.g., with a new test type), as long as it doesn't take TOO long to run.

**Comment by billsacks** [comment]
Looking at a recent run of this test that @ekluzek did, it looks like it's running at about 15 seconds per model day. Having a slightly-greater-than-one-year version of this test (starting Jan 1, still running in debug mode) would therefore fit just within the limit of what I'd consider reasonable (I consider anything over 2 hours to be too long for a test). We could double the processor count to improve this somewhat (though I don't think this f10 resolution scales fantastically).

**Comment by billsacks** [comment]
This seems to have been fixed by ctsm1.0.dev036, though I can't completely understand why. (I can't understand (1) why the bug that was fixed in ctsm1.0.dev036 led to this C balance error, given that the time step's C balance checks are initialized after the buggy fluxes; and (2) why this bug would have led to a problem in a decStart test but not a multi-year test that starts in Jan 1.)
