### ISSUE TITLE
Landunit-level NEE, TOT_WOODPRODC, CROPPROD1C requested by CMIP6 are only defined at gcell level

### ISSUE THREAD

**Issue by olyson** [ESCOMP/ctsm#420]
### General Type of Issue:
Enhancement

### Details of Issue:
There are CMIP6 variable requests for landunit-level (land-use tiles) NEE, TOT_WOODPRODC, CROPPROD1C.  But these are only defined at the gridcell level in the code (e.g., nee_grc).  Consequently, adding these to the history file streams with hist_type1d_pertape = 'LAND' crashes the model.
Not sure how this can be fixed or even whether this should be fixed at this time.

**Comment by dlawrenncar** [comment]
These terms are intentionally at grid cell level because TOT_WOODPRODC,
CROPPROD1C 'lose' their affiliation with a landunit after harvest.  This
avoids these pools from having to be adjusted due to changes in landunit
weights.  NEE includes the fluxes from these pools and therefore is also
only available at the grid cell level.  For LUMIP, I think that NBP is the
more appropriate variable and I think we were not going to report the
PRODUCT pools for LUMIP on the land-use tiles for the above reason.
