### ISSUE TITLE
If user_nl_clm is in the REFCASE directory go ahead and use it

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/ctsm#430]
With upcoming changes for CTSM we figure we'll need a different finidat file for each future scenario, even when they are starting from the same year of a historical simulation. Rather than have a separate REFCASE directory for each it makes sense to make the standard to interpolate from that year. I want to propose a way for that to happen out of the box.

I propose that if a user_nl_clm file is in a REFCASE directory, that CTSM would go ahead and use it. The main use of this would of course be to set use_init_interp=T, by default. To add more control there could be a XML variable that is required to be set to activate it.

What does everyone think about this idea?

CC @billsacks @dlawrenncar

**Comment by billsacks** [comment]
How about this compromise solution: Introduce a new namelist option, `allow_init_interp` (I'm open to a different name). This works similarly to `use_init_interp`, but it only does interpolation if it's actually necessary: First it checks if the current initial conditions file is compatible with the configuration (I think we already have code to check this, though it could probably be made a little more stringent). Then it does interpolation if it's needed, but doesn't do interpolation if the initial conditions file is already compatible. With this change in place, I'm comfortable with @ekluzek 's proposed idea of adding user_nl_clm to the refcase – as long as we follow the rule that we should put `allow_init_interp` rather than `use_init_interp` in refcase directories. This would address most of my concerns.

If we do allow `user_nl_clm` in a refcase, this will need to be implemented carefully to ensure that that `user_nl_clm` is applied at the right time relative to any other `user_nl_clm`. For example, it should probably be applied before any testmods or user-specified usermods directories, so that the latter take precedent. One way to implement this could be to add the refcase directory to the list of usermods directories in case.py: `apply_user_mods`. But I don't know if that would end up being too general of a solution, applying more than is really desired in some cases???

**Comment by ekluzek** [comment]
I'm not sure I agree with @billsacks suggestions. So obviously we don't have consensus on this. I'm bringing this up for discussion again, because I have to do another "_v2" update to a REFCASE. I'm going to plan on keep doing that kind of thing, until we think we have a different solution to try.

**Comment by billsacks** [comment]
@ekluzek as I mentioned I'm open to your original suggestion - though I'd like to hear your thoughts on

> The biggest issue in my mind: It seems like this would require changing a refcase after the fact, by adding a user_nl_clm file that turns on interpolation once we see that it's going to be needed for that refcase. This requires either (a) making a new refcase, or (b) changing an existing refcase. We've seen that (a) is painful, and (b) seems risky, because you risk changing answers if someone tries to rerun an old case (if interpolation changes answers in any way).

I also noticed that, in https://github.com/ESCOMP/cesm/pull/67, @fvitt added `use_init_interp = .true.` for a given refcase. Is that a possible alternative solution? I don't feel like that solution is absolutely ideal, but I like it better than adding `user_nl_clm` to a refcase directory.

**Comment by ekluzek** [comment]
@billsacks, hmmm, since that's the case I need to update (as it didn't work for Chris), I'm guessing that change didn't work correctly. There might just be a bug with it, I'll look into that.

**Comment by billsacks** [comment]
Since we can't think of a solution that works any better than currently, we're going to close this.
