### ISSUE TITLE
Granularity of water tracer flux updates

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/ctsm#490]
Following the example of what's done for carbon isotopes, I'm imagining that the water tracer updates will (eventually) look like this, for any tracers where fractionation is not at play:

1. Do a bunch of flux calculations on the bulk water (involving multiple subroutine calls)

2. Update all water tracer fluxes based on the bulk fluxes, for all fluxes computed above

3. Do state updates based on these fluxes - both for bulk and tracers

This sequence might happen a few times, but not _many_ times.

An alternative would be to have many calls to update water tracer fluxes sprinkled throughout the driver loop: We'd compute one or a few water fluxes on the bulk, then update the single/few relevant water tracer flux(es), then compute one or a few more water fluxes on the bulk, then update the single/few relevant water tracer flux(es), etc.

I can see arguments both ways, but my gut inclination is to aim for the first – with relatively few calls to routines that update water tracer fluxes, basically waiting until the last possible moment to do those updates (just before the fluxes are needed for a state update). Initially, with the current poor separation of flux calculations from state updates in the biogeophysics code, we might have code that ends up looking more like the alternative, but I'm imagining that the long-term goal would be for the code to look like the first option.

Do others have thoughts / opinions / preferences? I'm especially thinking that @davidnoone @martynpclark @mathewvrothstein and @mvertens might have thoughts, but I'd welcome thoughts from anyone.

**Comment by davidnoone** [comment]
If the water state us updated sequentially the in main driver loop, then the tracer state (can relevant calls) would need to be updated in the same way and at the same time. I suspect (and am quite sure) this means several places for update calls for the tracers. (e.g., one after canopy hydrology, one after soil hydrology, one after lake hydrology, one after snow, ....).
Similarly, in places where there are substepping done i the hydrology, we might need to consider also substepping the tracers. (I can imagine working around this, but it will require careful thought about which non-linearities we'd like to resolve vs ignore).

I think the long term goal is admirable: if it can be done that way for the bulk, then it could be done that way for tracers too.

**Comment by davidnoone** [comment]
@billsacks ...umm... yes. As a rule. But we might need go to specifics. The key is that the tracer fluxes (in general) depend on bulk state and the tracer state. So when there are partial updates done for bulk, the tracer fluxes need to be computed before the bulk update, and then subsequent flux calculations used both partially updated bulk and partially updated tracer. So you need to compute the tracer fluxes based on the partials, and do the partial updates of tracers with any partial updates of the bulk water.

Consider the following order of operations for 1 partial calculation. 

! good :)
evap = 1
tracer_evap = evap*tracer_h2osoi/h2osoi
h2osoi = h2osoi - evap
tracer_h2osoi = tracer_h2osoi - tracer_evap

! Same code, different order, BAD :(
evap = 1
h2osoi = h2osoi - evap
tracer_evap = evap*tracer_h2osoi/h2osoi
tracer_h2osoi = tracer_h2osoi - tracer_evap

Since the tracer_evap depends on the un-updated h2o, it needs to be calculated prior to the update. It is easy to get the order of operations wrong if everything is saved until the end. 

Exactly what the order of operations needs to be depends on which combination of fluxes. One particular area where this comes up in CLM and other models is where there are various limiters and fixes.

**Comment by billsacks** [comment]
@davidnoone Thanks a lot for this. This makes sense. Your explanation and example are very helpful.

I'm going to close this discussion issue, because I think I understand this well enough for now, but others can feel free to chime in if you have anything to add.
