### ISSUE TITLE
Add a multi-instance FATES test to the FATES test suite

### ISSUE THREAD

**Issue by rgknox** [ESCOMP/CTSM#514]
Several FATES researchers are using multi-instance with FATES.  
I think this needs a test, at least added to category="fates"

I was thinking:

NCK_Ld9.f10_f10.I2000Clm50FatesGs  

(NCK) is the multi-instance header right?

@billsacks , @ekluzek , any thoughts, and/or do you want this test also added to aux_clm?

**Comment by billsacks** [comment]
Sounds good. Yes, NCK is a multi-instance test. Note that this test is fairly weak: it ensures that you can run with 2 identical instances, and compares one of them (or maybe both?) to an identical single-instance run. There is recognition that a stronger test is needed, but nobody has taken the time to write one (e.g., see the discussion in https://github.com/ESMCI/cime/issues/445).

Another option is to do something like ERP_N2, which does a two-instance ERP test (confirming that both instances start up from restart properly). It might be worth having both an NCK and an ERP_N2 FATES test in the FATES test list. I don't think we necessarily need them in the aux_clm test list: generally, if multi-instance breaks, it's because of something at a very high level in CTSM (e.g., in the coupling layer), so it generally doesn't seem necessary to test multi-instance with different options on/off - but I can see how you'd want this in the fates test list to ensure yourselves that this is working with fates.

**Comment by rgknox** [comment]
>I don't think we necessarily need them in the aux_clm test list: generally, if multi-instance breaks, it's because of something at a very high level in CTSM (e.g., in the coupling layer), so it generally doesn't seem necessary to test multi-instance with different options on/off - but I can see how you'd want this in the fates test list to ensure yourselves that this is working with fates.

Makes sense.

But I am starting to wonder now if this is really a test needed for FATES run specifically.  It seems that the multi-instance functionality is fairly orthogonal to anything FATES relevant.  I brought up the idea for creating this test, because @ckoven was having multi-instance failing on edison.  But that seems to really be more of a machine compatibility issue, and not a fates vis-a-vis multi-instance issue...  Although, I suppose that is why we test, because we don't know what will be a problem, until it fails...

**Comment by billsacks** [comment]
I don't have strong feelings on this. Again, my experience is that, like you say, multi-instance is pretty orthogonal to anything related to specific options. However, there could be aspects that I'm not thinking of, such as if FATES handles any of its own creation of input / output file names.

**Comment by glemieux** [comment]
After discussing this with @rgknox and @ckoven in out fates team meeting today, we agreed that we should close this given that an `NCK` test exists in `aux_clm` and that multi-instance simulations have been successful since this time.
