### ISSUE TITLE
Why wa_col is set to aquifer_water_baseline?

### ISSUE THREAD

**Issue by bishtgautam** [ESCOMP/ctsm#524]
At beginning of the column-level water balance in [BalanceCheckMod.F90#L151](https://github.com/ESCOMP/ctsm/blob/master/src/biogeophys/BalanceCheckMod.F90#L151
), `wa_col` is set to `aquifer_water_baseline` if `zwt(c) <= zi(c,nlevsoi)`.  Though, `wa_col=aquifer_water_baseline` will not impact instantaneous water balance, it will impact water balance that is temporally integrated across multiple timesteps (i.e. use begwb at the beginning of the month, use endwb at the end of the month and temporally integrated fluxes over the month). The imbalance arises because the difference in water (i.e. `wa_col(c) - aquifer_water_baseline`) is not accounted as a source or sink of water. Why `wa_col` is set to `aquifer_water_baseline`?

**Comment by billsacks** [comment]
I thought I was the one who introduced this, but it turns out that I only changed the hard-coded 5000 to a named constant. This has been in place since clm3_6_57. It was apparently introduced as part of fixing http://bugs.cgd.ucar.edu/show_bug.cgi?id=1077. I don't know the reason for it, but from various comments, it looks like @ekluzek @jonbob @olyson @swensosc and @dlawrenncar were involved in this change 9 years ago.

I was curious about this, because @swensosc has proposed removing this block of code in a recent PR: https://github.com/ESCOMP/ctsm/pull/523/files#diff-eed0f8e2d5f4c88ae720743df1292e47 . @swensosc - are you able to comment at all on why this was there before and why you were able to remove it in your branch?

**Comment by bishtgautam** [comment]
FYI,  When Jon Wolfe ran a fully-coupled E3SM simulation with `wa(c) = aquifer_water_baseline` commented out (equivalent to [BalanceCheckMod.F90#L151](https://github.com/ESCOMP/ctsm/blob/master/src/biogeophys/BalanceCheckMod.F90#L151)), the net land water budget outputted in the coupler logfile was improved by a factor of 3.5.

From a 20-year E3SM run:
Before the fix: land net water budget 0.17404634
After the fix   : land net water budget   -0.04947601

**Comment by billsacks** [comment]
@bishtgautam sorry this never received any comments from us. But I think we generally agree with the idea of removing it, so I have opened #596 . Did you guys ever determine if anything needs to be done in place of this code, or if it's safe to simply remove this block of code?

**Comment by bishtgautam** [comment]
Simply removing the code block is safe.

**Comment by billsacks** [comment]
Okay, thanks. I'll close this issue, just leaving #596 open.
