### ISSUE TITLE
is rsmax0 needed/redundant?

### ISSUE THREAD

**Issue by rgknox** [ESCOMP/ctsm#594]
(EDITED, I HAD MY MIN/MAXES FLIPPED)

rsmax0 is a cap that ensures stomatal resistance does not exceed a maximum (EDITED).  It is mostly found in the photosynthesis scheme, initialized here: 

https://github.com/ESCOMP/ctsm/blob/master/src/biogeophys/PhotosynthesisMod.F90#L1573

It is applied after stomatal conductance is calculated, and I think that it is applied after stomatal conductance has been iteratively co-solved to find a net assimilation rate.   

I was working through very similar code in FATES, and my concern was that by capping  resistance at rsmax0, the resistance that is passed to hydraulics and transpiration is disconnected from the resistance that actually calculated co2 flux.

Is there a reason why the capping on stomatal conductance is not being applied in the routines where it is first calculated, so that there is consistency with the value that dictates CO2 flux?

**Comment by billsacks** [comment]
@olyson I'm tentatively assigning this to you to either answer yourself or reassign as you see fit.

**Comment by olyson** [comment]
I don't know the answer to this.  I'll have to check in with Gordon next week.

**Comment by olyson** [comment]
I'm just adding an email exchange to this:

thanks Gordon.
It does seem so small that it will act as a numerical protection and not compromise results.


On Mon, Dec 17, 2018, 10:34 AM Gordon Bonan <bonan@ucar.edu wrote:
Ryan,

I cannot speak to FATES, but in CLM5 rsmax0 is used in PhotosynthesisMod. It provides a small minimum conductance so that conductance is not zero (which might cause problems in other parts of the model). The resulting conductance is very small (about 0.002 mol/m2/s vs. 0.2-0.4 mol/m2/s for open stomata).

Gordon

**Comment by rgknox** [comment]
Thanks @olyson , I'm fine with closing this up if desired.
