### ISSUE TITLE
Pull some hard-coded parameters out to netcdf file

### ISSUE THREAD

**Issue by negin513** [ESCOMP/ctsm#680]

**Comment by slevisconsulting** [comment]
For reference, this is  @katiedagon 's list of parameters:
https://docs.google.com/spreadsheets/d/1cRmcB0xz7CjVP6ljUoCehJx49Usxsore5ma4mWcvQwM/edit#gid=0

**Comment by slevisconsulting** [comment]
@katiedagon tells me that she pulled some of the parameters out to the namelist. So question...

Are we pulling params to a netcdf file (as the issue is titled) or to the namelist? OR should we decide one parameter at a time? And might some parameters belong in the  paramfile = '/glade/p/cesmdata/cseg/inputdata/lnd/clm2/paramdata/clm5_params.c171117.nc'

**Comment by katiedagon** [comment]
Great question! This came up during the last CLM meeting, when @billsacks was discussing whether we should include all of the default namelist values in the current lnd_in file. 

The way I see it, the current paramfile (netcdf) is for PFT-dependent parameters, so they have that extra dimension of variability. The parameters I identify in the spreadsheet probably do not fit this criteria, though there could be others that do. Some of this depends on whether we want to develop PFT variation for parameters previously thought to be constant across PFTs, so it is probably something that should be considered on a case-by-case basis.

For my work I had to pull some hard coded parameters into the namelist because I was running perturbed parameter ensembles and didn't want to deal with SourceMods and re-compiling each time. The ones I pulled out were not PFT-dependent, so the namelist seemed like the best place for them at the time.

**Comment by ekluzek** [comment]
Yes, we've gone back and forth on this. There are some scalar parameters that are on the PFT paramfile, and there are some that in namelist. At one point we were going to put all parameters on the same paramfile. But, then we started only putting the PFT dependent ones, and the scalars in the namelist. Now, as a longer term goal we want to have everything on a netCDF file. So as a short term goal putting scalars in the namelist and PFT-dependent parameters on the paramfile as @katiedagon outlines is a good way to go.

@katiedagon do you have a branch in git, where we could see your changes and start moving them to CTSM master?

**Comment by slevisconsulting** [comment]
Another question for you @katiedagon 
Could you add a couple of new columns to the google sheet as follows?
- Moved to namelist (Yes/No)
- Pft dependent (Yes/No)

**Comment by katiedagon** [comment]
@ekluzek Yes, it is located here: https://github.com/katiedagon/ctsm/tree/ParamEns
And the specific commit where I made the code modifications is here:
https://github.com/katiedagon/ctsm/commit/4f353409f890d2068b2cb0d0f7c4fb928bdd85ae

I tried to follow the code for examples of creating new namelist parameters, but if there are best practices I should be following please let me know.

@slevisconsulting I added the first column to the google sheet, the second column I will need to think about a little more, especially which ones are "Maybe". I can take another look tomorrow.

**Comment by billsacks** [comment]
Putting these scalar parameters on the namelist is fine, especially if @katiedagon has already done some work along these lines.

However, I want to mention: In CLM software meetings over the last few months, we had come up with the plan of moving any new real-valued parameters to the netcdf file rather than to the namelist file. The rationale is that that moves us closer to the long-term direction of where we want to be, and causes less of a need for redoing work. 

Specifically: Broadly speaking, there are three things that need to be done to add a new namelist parameter: (1) add it in the xml (namelist definition & defaults), (2) add it in CLMBuildNamelist, (3) add it in the Fortran. (1) & (2) are typically straightforward, whereas (3) can take a fair amount of code, particularly for modules that do not yet have any namelist parameters. Given our long-term plan, any work on (3) would be wasted effort long-term, which was part of the motivation for the above decision. In contrast, if we put new parameters on the netCDF params file, then the Fortran code to read in those parameters will most likely remain the same with our long-term plan.

The downside of this plan is that, in the short term (until we have all of our intended infrastructure in place), it may be harder for some users to modify these newly-extracted parameters than if they were on the namelist (but hopefully still easier than when they were hard-coded).

I don't feel strongly about this, but I do have the feeling that it's not worth writing a lot more Fortran namelist-reading code that we'll just have to delete in a year or so, so if we pull parameters to namelist rather than netcdf, the focus should probably be on parameters in modules that are already reading something off of the namelist.

Again, though, if Katie already has code that extracts some parameters, we might as well at least bring that in, since the work is already done.

**Comment by ekluzek** [comment]
@billsacks that's my view as well. Since, @katiedagon has already moved some things to namelist and has a branch for that -- we might as well take advantage of that in the short term. But, new work should put parameters on the paramsfile. So I think you and I are in sync on that. But, not everyone has been in all the discussions we've had on this.

**Comment by billsacks** [comment]
> But, not everyone has been in all the discussions we've had on this.

Yup, sorry: I didn't mean for my comment to sound like, "Hey, we've already talked about this!" Rather, I wanted to bring people that haven't been in the loop into the loop (with apologies for not doing so earlier!)

**Comment by dlawrenncar** [comment]
Not clear to me why we would not start now with putting all newly pulled
parameters o to the netCDF file. We are going to move that way at some
point anyway so might as well start now, right?

On Apr 11, 2019, at 5:29 PM, Erik Kluzek <notifications@github.com> wrote:

Yes, we've gone back and forth on this. There are some scalar parameters
that are on the PFT paramfile, and there are some that in namelist. At one
point we were going to put all parameters on the same paramfile. But, then
we started only putting the PFT dependent ones, and the scalars in the
namelist. Now, as a longer term goal we want to have everything on a netCDF
file. So as a short term goal putting scalars in the namelist and
PFT-dependent parameters on the paramfile as @katiedagon
<https://github.com/katiedagon> outlines is a good way to go.

@katiedagon <https://github.com/katiedagon> do you have a branch in git,
where we could see your changes and start moving them to CTSM master?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ESCOMP/ctsm/issues/680#issuecomment-482371757>, or mute
the thread

**Comment by ekluzek** [comment]
@dlawrenncar that is what we are proposing at this point. We want to adopt @katiedagon's branch, just because it's already been done. But, for new work, they should be added to the paramfile regardless of what type of field they are (scalar or PFT dependent). There will still be more work when we have the full vision of fields in the XML database, and the paramfile created as part of buildnml. But, the read in the FORTRAN code -- won't have to be redone (like it would if it's a namelist item) -- which is a good point that @billsacks makes.

**Comment by slevisconsulting** [comment]
I support the decision to add new parameters to the params.nc file. 

I have now also looked @katiedagon 's branch here  katiedagon@4f35340 . In this branch Katie placed 2 of the 21 parameters in the namelist. Is it still worth starting from Katie's branch for these two parameters, or should I place all 21 parameters in the params.nc file? I vote for the latter and am not attached either way.

**Comment by billsacks** [comment]
Either way is fine with me.

**Comment by ekluzek** [comment]
Up to you @slevisconsulting. I was envisioning that perhaps Katie's branch had many parameters converted.  Using her branch would probably make it easier for her to use immediately. But, since we want these things on the paramfile in the longer term, it doesn't matter too much if it's just two parameters....

**Comment by slevisconsulting** [comment]
**STEP 1.**  Created new params.nc file with data from @katiedagon 's google sheet (link avail. near the top of this page). Lead reviewer for this issue (and/or others), pls review the new file:

/glade/p/cesmdata/cseg/inputdata/lnd/clm2/paramdata/clm5_params.c190412.nc

**Comment by slevisconsulting** [comment]
BTW thank you @katiedagon for compiling the google sheet; it has already been very helpful. 

I ended up using the "PFT-dependent" column info to set the pft-dependent parameter dimensions to "allpfts" and the pft-independent parameter dimensions to scalar. The dimension allpfts was already in the file and set to 1.

**Comment by slevisconsulting** [comment]
Next I envision doing the following...
- Change default namelist entry for paramfile
- Test on hobart: expect bfb to baseline
- Modify pftconMod.F90 to read the new parameters
- Transmit the new parameters to their respective pieces of code
- Remove obsolete declarations of same hardwired parameters
- Test on hobart first: expect bfb to baseline

**Comment by billsacks** [comment]
A couple of comments:

(1) Let's put the param reads in the module where we need a given param

(2) Change code like this:

```fortran
     tString='q10ch4'
     call ncd_io(trim(tString),tempr, 'read', ncid, readvar=readv)
     if ( .not. readv ) call endrun(msg=trim(errCode)//trim(tString)//errMsg(sourcefile, __LINE__))
     params_inst%q10ch4=tempr
```

to ideally a one-line call to some utility function. See paramUtilMod for something you may be able to use for that.

**Comment by slevisconsulting** [comment]
At today's CLM Software Update meeting we decided to remove the allpfts dimension entirely from the params.nc file.

**Comment by slevisconsulting** [comment]
Dimension allpfts removed. I have replaced the params.nc file with this one:
/glade/p/cesm/cseg/inputdata/lnd/clm2/paramdata/clm5_params.c190416.nc
