### ISSUE TITLE
Use of --extra-create-test-args " -r cases" to run_sys_tests, puts "cases" under HOME directory on hobart 

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/ctsm#693]
### Brief summary of bug

It doesn't do this on cheyenne, but only hobart. By my adding the directive to put the test cases under the "cases" subdirectory puts it under $HOME/cases. On cheyenne it puts it under $CTSMROOT as I would expect it to.

### General bug information

**CTSM version you are using:** ctsm1.0.dev036
**Does this bug cause significantly incorrect results in the model's science?** No

**Configurations affected:** run_sys_tests on hobart
### Details of bug

``` cshell
./run_sys_tests -c ctsm1.0.dev035 -g ctsm1.0.dev036 -s aux_clm --extra-create-test-args " -r cases -o" \
                   --testid-base ctsm1d36a
```

**Comment by billsacks** [comment]
Keep in mind that run_sys_tests runs the create_test command via a batch job. So I think this is a result of what directory you're in when a batch job starts up. On hobart, I guess you start out in your home directory, rather than the current directory, so all paths you specify are relative to that.

Taking a step back, you may want to consider if there is still value in specifying '-r cases' with some of the run_sys_tests features. Specifically, note that run_sys_tests gives you a sym link in your current directory pointing to the directory where all cases will appear (e.g., `tests_0424-120505ho`). So you can easily get to your cases from your current ctsm directory, and furthermore, all run directories will then be nested under your case directories. (The latter was recently implemented in run_sys_tests by @negin513 and I find it to be a very helpful feature.) In fact, there may be aspects of run_sys_tests that don't work correctly if you try to override the test-root, because it expects a certain organization of the test directories.

For all those reasons, I'm tempted to close this as a wontfix, but you can let me know what you think.

**Comment by ekluzek** [comment]
That make sense. That is how batch works on hobart. I mistakenly thought it might be hardcoded into the script, and if so I wanted to remove that. Yeah, since I'm converting from how I used to run to using run_sys_tests, I'll try out the way it runs it and see what I think. It's possible I don't need the "-r cases" anymore. I explicitly use that name, because there is a gitignore for cases under cime/scripts. But, the softlink to the whole bunch under scratch might really give me what I need. So I'll start trying that and get back to this issue.
