### ISSUE TITLE
New high resolution PFT data has a different landmask over Antarctica

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/ctsm#697]
The new high resolution PFT raw data file has a slightly different landmask than the previous one. The difference is ONLY over Antarctica. Since, most of Antarctica is 100% glacier, this change won't actually make a difference EXCEPT for some coastal points that have some bare soil. I've got the process to work using the old landmask, but updating the landmask would take some effort. A new SCRIP grid file for the new landmask with an updated name, and then new mapping files for ALL the supported resolutions. This effort doesn't seem worth the cost for such a small impact. Especially since this dataset is especially for use for regional grids, most of which won't even include Antarctica. I have not as of yet created the new landmask to verify what the difference would be. But, we know it will be small and only involve the Coastal points around Antarctica, so it doesn't seem worth the effort at this time.

If we think we have a reason that we should look into the impact or go through the full process with the mapping files, we can do that at a later date. Right, now my plan is to leave this as it is.

@lawrencepj1 @barlage @billsacks

**Comment by billsacks** [comment]
Summarizing the discussion I just had with @ekluzek 

If the difference is that the new dataset has land in a small number of points where the old had ocean, then this doesn't seem like a big deal: those points would just be treated as ocean, as they were before.

However, if the difference is that the new dataset has ocean where the old had land, then we need to confirm that the new dataset has reasonable values even for points outside its mask, because those points outside the mask will contaminate the averaging. In this case, it might take less effort to just make new mapping files than it would to figure out if we're safe to use the old mapping files.

**Comment by ekluzek** [comment]
OK, comparing the old and new masks, I *thought* the change was just over Antartica at first. But, looking up close it's around all coastlines. I'm generating new maps and will do some evaluation of the difference it makes.

**Comment by ekluzek** [comment]
The difference in the mask does make some difference over all coastlines for f09 surface datasets, but interior looks unaffected. While the upgrade to the high resolution dataset does have an impact on the interior as expected. So the difference between the two masks isn't too big of a deal, but, we might as well get the correct masks going out of the box.

**Comment by ekluzek** [comment]
release-clm5.0.21 gets the right SCRIP grid file in place and release-clm5.0.22 puts in most of the needed mapping files in place.
