### ISSUE TITLE
Some stream years are incorrect out of the box for SSPs

### ISSUE THREAD

**Issue by olyson** [ESCOMP/ctsm#700]
### Brief summary of bug

Some namelist items associated with streams are incorrect out of the box for SSPs

### General bug information

relcisofix.n01_release-clm5.0.20

**Does this bug cause significantly incorrect results in the model's science?** [Yes / No]

Yes.  These compsets are affected: BSSP585, BSSP126, BSSP245, BSSP370

### Details of bug

The following settings are incorrect:
model_year_align_ndep = 1850
ndep_taxmode = 'cycle'
stream_year_first_ndep = 1850
model_year_align_popdens = 1850
stream_year_first_popdens = 1850
model_year_align_urbantv = 1850
stream_year_first_urbantv = 1850

We had fixed these using the following in use_nl_clm in the SSP585 case Nan R. ran:
 model_year_align_urbantv = 2015
 model_year_align_popdens = 2015
 stream_year_first_popdens = 2015
 stream_year_first_urbantv = 2015
 model_year_align_ndep = 2015
 stream_year_first_ndep = 2015
 ndep_taxmode = 'extend'

### Important details of your setup / configuration so we can reproduce the bug

This is present in test cases are being setup for the SSPs:
/gpfs/fs1/scratch/fischer/ERS.f09_g16.BSSP585.cheyenne_intel.allactive-cmip6_deck.cesm2control
/gpfs/fs1/scratch/fischer/ERS.f09_g16.BSSP370.cheyenne_intel.allactive-cmip6_deck.cesm2control
/gpfs/fs1/scratch/fischer/ERS.f09_g16.BSSP245.cheyenne_intel.allactive-cmip6_deck.cesm2control
/gpfs/fs1/scratch/fischer/ERS.f09_g16.BSSP126.cheyenne_intel.allactive-cmip6_deck.cesm2control

**Comment by ekluzek** [comment]
@olyson we should discuss this a bit. The 1850 start/align years comes over from the CMIP5 rcp settings. If the start and align agree it should have the correct alignment. So should give correct results. The advantage of having 1850 over 2015 though is that you can use future scenarios for historical simulations as a way to have data beyond the current end of our data.

ndep_taxmode is definitely wrong and should be changed so that you can run simulations beyond 2100. It isn't a problem for simulations less than 2100.

**Comment by olyson** [comment]
I guess I can see that the urbantv and popdens are ok then, although I'm not sure why we had decided to change it in Nan's SSP585 simulation.
But the ndep data goes from 2014 to 2101.  Will the right data be read in if stream_year_first_ndep = 1850 and model_year_align_ndep = 1850?

**Comment by mvertens** [comment]
Will this effect the simulations we are setting up. It would be good to
confirm this before we create the experimental tags.

**Comment by ekluzek** [comment]
@olyson it will do the right thing, although it looks wrong. If it weren't getting the right year we'd likely see it in our testing already. I think the reason we changed it for Nan's simulation was that we gave her the changes to make by hand rather than referring to the CMIP5 cases.

With a lot of these datasets I've tacked the historical part on the front of the SSP periods, to make them more flexible to use. I wonder if we should do that with the ndep datasets as well?

So this should all work as is and give the same results for these simulations as we expect. But, I think we should probably at least do one test to verify that it really is the case.

**Comment by olyson** [comment]
I looked at Chris' SSP585 test and it is reading in time samples 12 and 13 from the ndep file at the start of the simulation.  Which should be Dec, 2014 and Jan, 2015, and is correct.  
I also checked the popd and urbantv streams and the right time slices are being read in as well.
So I agree that all is working correctly.

We could discuss tacking on the historical at the beginning of the ndep (and aerosol) files.  Although I think we had a discussion about whether it was worth increasing the size of these files to do that.  We would have at least four SSP files that had the same historical data tacked onto the beginning.

**Comment by ekluzek** [comment]
We talked about this at our CLM software meeting. The use case of using a SSP to get more recent data is a common one -- but a special case. And it's something that you would need to make changes for anyway. So we should set this up out of box to be specific for the standard SSP cases that we are doing. The start/align years here aren't "wrong" -- but it looks a bit odd. So I'll update them as we say here.

We also thought that we should use "limit" for ndep so that it would abort once it gets to the end of 2100. This will then require the user to do something thoughtful to extend the simulation beyond 2100 cycling over years that they pick so you get a seasonal cycle rather than just using the last monthly value.

**Comment by ekluzek** [comment]
Fixed in release-clm5.0.21
