### ISSUE TITLE
Ball-Berry parameters in CLM5.0 should go back to the previous values in CLM4.5

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/ctsm#705]
Gordon Bonan brings this up. The Ball-Berry parameters were adjusted in an attempt to tune CLM5.0, and the tuning wasn't satisfactory. The satisfactory tuning involved the new Medlyn photosynthesis. So if you use Ball-Berry in CLM5.0 you should use the previous values rather than the new ones.

**Comment by billsacks** [comment]
My understanding (without looking carefully) is that this impacts cases that use clm50 physics but manually change to using Ball-Berry, or turn PHS off (which also causes you to revert to Ball-Berry); this also impacts the new NWP configuration, which uses Ball-Berry by default.

Since clm4.5 uses a different params file, I'm guessing that is *not* affected, but I haven't actually checked that myself.

**Comment by ekluzek** [comment]
CLM4.0 had: 9, 6, 6, 6, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 5, 9, 9, 4, 9, 9, 9
CLM4.5 has: 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 4, 9, 9, 4, 4, 9, 9 note 2nd-4th are 9 rather than 6, 15th is 4 rather than 5 and 19 is 4 rather than 9
CLM5.0 has: 9, 4.4713363873471, 7.10166797896943, 7.10166797896943, 
    7.29147600379525, 7.10166797896943, 7.1797077457757, 7.10166797896943, 
    7.10166797896943, 7.10166797896943, 7.10166797896943, 7.10166797896943, 
    7.10166797896943, 9.75753228727652, 9.75753228727652, 9.75753228727652, 
    9, 4, 4, 9, 9

(So first and last five are the same as CLM4.5)

**Comment by ekluzek** [comment]
Gordon Bonan replies on this that the CLM4.5 values should be used

> "Thanks for following up on this. The correct values to use for mbbopt are those from CLM4.5. There are only two unique values: 9 for C3 plants and 4 for C4 plants."
