### ISSUE TITLE
CLM misses history variable for radiative surface temperature

### ISSUE THREAD

**Issue by lvankampenhout** [ESCOMP/CTSM#715]
### Brief summary of bug
In CAM, history variable `TS` represents the radiative surface temperature. Over land, this is passed from CLM :

```
lnd2atmMod.F90

117     do g = bounds%begg,bounds%endg
118        lnd2atm_inst%t_rad_grc(g) = sqrt(sqrt(lnd2atm_inst%eflx_lwrad_out_grc(g)/sb))
119     end do
```
However, there is no equivalent history output field in CLM, and since the conversion from upwelling longwave radiation to radiative temperature is non-linear, it is also impossible to derive it afterwards. 

For my application I need TS per elevation class in CLM, so it would be great if this history variable can be added in the future, yet may be inactive by default. 

### General bug information

CESM 2.1

**Does this bug cause significantly incorrect results in the model's science?** [No]

**Comment by billsacks** [comment]
@lvankampenhout thanks for this good suggestion.

I'd like to better understand exactly what you'd like. We could make a diagnostic field that gives `t_rad_grc`. That would be easy, but that would just be gridcell-level. It sounds like you want something that is patch-level, which would involve doing the above calculation on the original patch-level version of `eflx_lwrad_out_patch`. Is that correct? If so: Note that (I think) the gridcell average of this new patch-level variable would differ from an output value of `t_rad_grc`, because of non-linearities... I'm not sure if that's a problem for you.

We don't have an easy way to turn off diagnostic calculations when the relevant history field isn't requested, and I'm just a bit hesitant to add this extra calculation to the model if it's only wanted for one application. So if this is what you want, I'll want to check in with a couple of other people to see if it might be more generally useful; otherwise, I'll probably suggest that you do this on a branch.

**Comment by billsacks** [comment]
@lvankampenhout - @dlawrenncar pointed out that there is a TSKIN diagnostic variable at the patch-level that gives basically what you want. It's not exactly the same as what CAM sees, but it's better in some sense, in that it uses the actual emissivity of each patch. Does that give you what you need, or do you need exactly what's sent to CAM? (If the latter: Since there is already this TSKIN variable, I'm guessing there isn't going to be a lot of support for adding another patch-level variable that is more closely equivalent to what is sent to CAM, but it would be easy enough to add an optional gridcell-level diagnostic that equates to CAM's TS, if that would be helpful.)

**Comment by lvankampenhout** [comment]
Hello @billsacks, thanks for considering my suggestion and sorry for the ambiguity in the original request. But it's like you say, I'm interested in a patch-level variable representing `eflx_lwrad_out_patch`, so it would vary across multiple elevation classes on a glacier. 

I've had a look into the TSKIN variable that you suggested. Although it appears to suffer from the same problem as TG did for glaciers, it is quite interesting. Compare the following two plots, where I compute differences between CAM TS and CLM TG/TSKIN

TG
![camTS-clmTG](https://user-images.githubusercontent.com/7933853/59202941-dddec000-8b9d-11e9-894f-30ba5934b911.png)

TSKIN
![camTS-clmTSKIN](https://user-images.githubusercontent.com/7933853/59202942-dddec000-8b9d-11e9-8ffb-f5db7abaec3f.png)

Over vegetated areas, differences seem to vanish. However, over non-vegetated areas and over lakes, differences remain (+ over lakes, - over bare land and glacier). I have tried to make sense of this by looking at the code, but could not find a reason why TSKIN equals CAM TS over veg, but not elsewhere. Any ideas? Non-linearities from patch to gridcell can be excluded I think, since some areas (e.g. Sahara, Antarctica) are rather flat. 

Understanding this difference could be more relevant than the actual implementation of my feature request.

**Comment by billsacks** [comment]
@lvankampenhout - based on what @dlawrenncar told me a few weeks ago, I think TSKIN uses the actual emissivity of each patch, whereas CAM's TS uses some assumed or average emissivity. I'm not sure of the details, but I'm guessing that, if you dug into the calculation of TSKIN, you'd find some surface emissivity that goes into the calculation. If you plotted that emissivity or corrected for it somehow, my hope is that you could reconcile the differences you're seeing.

**Comment by lvankampenhout** [comment]
@billsacks - I believe that CAM TS is nothing else than `eflx_lwrad_out_grc` converted to temperture, see my initial post. It hurts my head trying to understand why TS (apparently) equals TSKIN over veg columns, but not over bare columns. If there is a scaling involved -- like you suggest --  would that scaling not apply to both types? 

I plan on revisiting this issue whenever I have more time.

**Comment by billsacks** [comment]
Hmmm, looking very quickly at the code, I'm having trouble reconciling the code with @dlawrenncar 's statement that TSKIN uses the actual emissivity of each patch. This may be true for vegetation, but for non-vegetated patches, I see:

https://github.com/ESCOMP/ctsm/blob/2632be6af65ad7d1c0d23ae501c76b3cf68d0d6c/src/biogeophys/SoilFluxesMod.F90#L417-L425

My new hypothesis is that the differences you're seeing are due to non-linearities in the averaging: I think CAM's value is derived by taking the 4th root of the gridcell average lwrad, whereas TSKIN is derived by taking the gridcell average of the 4th root of patch-level lwrad values.

For example, if you have 2 patches, each with 50% area, one with lwrad = 100 W m-2 and one with lwrad = 200 W m-2, CAM would use the 4th root of 150 W m-2 = 3.50, whereas TSKIN would use the average of the 4th root of 100 and the 4th root of 200 = 3.16.

**Comment by dlawrenncar** [comment]
Yeah.  I recall that Ahmed said things were complicated when it comes to
calculating skin temperature.  I can't quite understand why the code looks
like it does, though.  Would have to go back and try to understand why he
made that decision.

**Comment by lvankampenhout** [comment]
@billsacks - if it is right what you're saying about non-linearities in the averaging, wouldn't that hold for TSKIN over vegetated grid cells as well? Or can it be coincidental that highly vegetated areas show up as 0's in the difference plot.

**Comment by billsacks** [comment]
> @billsacks - if it is right what you're saying about non-linearities in the averaging, wouldn't that hold for TSKIN over vegetated grid cells as well? Or can it be coincidental that highly vegetated areas show up as 0's in the difference plot.

Yeah, I'm not sure about that, other than thinking that, in vegetated grid cells, the different patches may have very similar lwrad values.

**Comment by billsacks** [comment]
@lvankampenhout I was reviewing some open issues, and I just wanted to check back about this one. Do you still feel like something is needed here - either in terms of additions to the code or further discussion? Or can I close it for now (in which case we could always reopen it later if needed)?

**Comment by billsacks** [comment]
Tentatively closing this issue. @lvankampenhout feel free to reopen if you feel anything still needs to be done here.
