### ISSUE TITLE
Crop GDD accumulation gives large weight to the first years

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/CTSM#75]
**Bill Sacks < sacks@ucar.edu > - 2017-12-06 10:32:11 -0700**
**Bugzilla Id:** [2544](http://bugz.cgd.ucar.edu/show_bug.cgi?id=2544)
**Bugzilla CC:**  dlawren@ucar.edu,  dll@ucar.edu,  lawrence@ucar.edu,  oleson@ucar.edu,  rfisher@ucar.edu, 

The crop GDD accumulation logic (in CNPhenologyClimate) gives disproportionately large weight to the first years when a crop is active: At the end of each year, it updates gdd020 (and similar variables) with:

gdd020(p)  = (yravgm1* gdd020(p)  + gdd0(p))  / yravg

where yravgm1 = 19 and yravg = 20.

This means that, at the end of yr2, gdd020 is (19*(gdd0 in year1) + 1*(gdd0 in year2))/20, etc.

This should probably be reworked to give all years equal weighting, e.g., by using the logic in accumulMod for running averages. Or better yet, this could be refactored to actually use accumulMod.

**Comment by billsacks** [comment]
@danicalombardozzi we discussed this today; just wanted to bring it to your attention (and I'm happy to discuss it further if you'd like).

**Comment by samsrabin** [comment]
Note that using `accumulMod` instead of this doesn't actually "give all years equal weighting." Doing that would require that we retain the last 20 years' values for every crop patch, which would presumably be too memory-intensive. However, using `accumulMod` _would_ solve the bug of weighting 19/20 and 1/20 no matter how many years the patch had been active.

(See [this comment](https://github.com/ESCOMP/CTSM/pull/2060#issuecomment-1690586790) on #2060.)
