### ISSUE TITLE
mksurfdata_map's Makefile.data should probably use a single processor on the share queue

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/CTSM#764]
In mksurfdata_map's Makefile.data, for each surface dataset, we currently request 2 processors on a node in the regular queue:

https://github.com/ESCOMP/ctsm/blob/05fca10c266f66c4de4f338a492c8dddc46e648f/tools/mksurfdata_map/Makefile.data#L41

Since mksurfdata_map isn't parallelized, this seems like a waste of resources (and amount charged to our account) to me. It seems like we should be using a single processor on the share queue for each process.

@ekluzek do you know if there was a reason why you set this up this way in the first place? Is it possible that there simply wasn't a share queue at the time, but now that there is it should be changed?

**Comment by ekluzek** [comment]
Hmmm, that's a good question. Yes, this does look wrong. I'm pretty sure it was setup before the share queue, so yes that's likely part of it. It's also asking for memory, and maybe the larger grids need a larger amount of memory. So that might be part of it too. It's probably only a few grids that need something different than a standard run in the share queue though. So this perhaps should be setup for a high resolution setup and a low resolution one.

Before this came in, the execgy script was used.

**Comment by ekluzek** [comment]
With #1663 this is no longer matters. The new mksurfdata_esmf will use multiple processors so this isn't an issue anymore.
