### ISSUE TITLE
Problems with rootr when use_hydrstress=.true.

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/CTSM#812]
### Brief summary of bug

In CLM50 cases, with use_hydrstress=.true., both rootr_patch and rootr_col have problems. These can be seen in the history fields ROOTR and ROOTR_COLUMN, and possibly impact the methane code.

### General bug information

**CTSM version you are using:** ctsm1.0.dev068

**Does this bug cause significantly incorrect results in the model's science?** Possibly

**Configurations affected:** I think this affects configurations with use_hydrstress=.true., though I'm not totally sure that that's the correct set of configurations affected.

### Details of bug

There are two problems here, possibly related or possibly independent:

(1) rootr_patch (ROOTR diagnostic field) is 0 over all vegetated points in a CLM50 configuration. I observed this in `SMS_D_Ld1_P4x1.f10_f10_musgs.I2000Clm50BgcCropQianRsGs.bishorn_gnu.clm-default`, by adding ROOTR to the h0 file, and also changing ROOTR to use `l2g_scale_type='veg'`.

My best guess (though I could definitely be wrong here) is that this is due to this code:

https://github.com/ESCOMP/CTSM/blob/1720bc754a75bbf3cab67424c63c292a2b6e45eb/src/biogeophys/SoilMoistStressMod.F90#L429-L439

Is btran always 0 in a case with use_hydrstress, so that the `else` clause is always entered in that configuration?

Looking at uses of rootr_patch: If we're using use_hydrstress = .true., it looks like the one place this will potentially impact the evolution of the system is in the methane code:

https://github.com/ESCOMP/CTSM/blob/1720bc754a75bbf3cab67424c63c292a2b6e45eb/src/biogeochem/ch4Mod.F90#L2920

In a CLM45 configuration (`SMS_D_Ld1_P4x1.f10_f10_musgs.I2000Clm45BgcCropQianRsGs.bishorn_gnu.clm-default`) this field is between 0 and 1, as it should be.

(2) rootr_col (ROOTR_COLUMN diagnostic field) has huge values (around 1e13) in a CLM50 configuration, whereas in a CLM45 configuration this field is between 0 and 1, as it should be (determined with the same tests as noted above). It looks like the code for calculating this variable differs depending on whether we're using use_hydrstress, so I again think that this bug is related to this option.

I can't tell if this indicates a real science problem (causing problems in the evolution of other fields) or if it's just a problem with this one diagnostic field.

**Comment by olyson** [comment]
I've been debugging with the test you ran and I'm also getting ROOTR zero everywhere.  
Looks to me that you are right that it's getting set to zero in that code section in SoilMoistStressMod.F90.   
This is happening because btran is set to btran0 (value of zero) initially in CanopyFluxesMod.F90 and then calc_root_moist_stress is called with btran = 0 soon after.  So rootr_patch is set to zero.  
It doesn't affect soil moisture stress when use_hydrstress = .true. because that doesn't use rootr_patch (see code in Compute_EffecRootFrac_And_VertTranSink_HydStress).  I agree that it could affect the methane code.  
With use_hydrstress = .false. I'm not sure what is happening yet, although you have noted that rootr_patch is between 0 and 1 in that case, so maybe it's ok.
Haven't investigated rootr_col yet either.

**Comment by olyson** [comment]
I think that with use_hydrstress=.false., rootr_patch is ok because it's calculated using the CLM45 method.
I'm not sure what rootr_col is supposed to represent but it makes sense that it could have large values (positive or negative) by layer because it's calculated as:

 rootr_col(c,j) = qflx_rootsoi_col(c,j)/sum( qflx_rootsoi_col(c,:))

qflx_rootsoi_col can be positive or negative (due to hydraulic redistribution) by layer, and the sum of qflx_rootsoi_col can be quite small and so rootr_col can take on large values.  An example:

 c:         1036
 j:           20
 qflx_rootsoi_col:  -1.601944883602759E-013
 sum(qflx_rootsoi_col):   7.573064690121713E-029
rootr_col: -2.115319159616227E+015

Luckily, rootr_col doesn't seem to be used anywhere.  qflx_rootsoi_col is used in SoilWaterMovement to extract or add water to soil layers.
If rootr_col is intended simply as a diagnostic then I suggest we don't calculate it when use_hydrstress=.true.  
It seems to be ok when use_hydrstress=.false. because then it's calculated based on reasonable rootr_patch values.

**Comment by olyson** [comment]
Looks like my change to calculate btran in SoilMoistStressMod.F90 regardless of use_hydrstress is bfb with the methane model off, but not with it on.  So the changes to rootr as used by the methane model apparently may feed back to the rest of the model.

I've pushed the following changes to my branch:
1. Calculate btran in SoilMoistStressMod.F90 regardless of use_hydrstress
2. Comment on the applicability of this calculation and that of rootr in SoilMoistStressMod.F90
3. Add the following comment to uses of rootr and rootr_col throughout the code: "SMS method only"
4. Allow ROOTR_COL history field only if use_hydrstress = .false.
5. Remove the calculation of rootr_col in subroutine Compute_EffecRootFrac_And_VertTranSink_HydStress within module SoilWaterPlantSinkMod.F90 since that calculation is invalid for PHS.
6. Normalize root resistances for pervious road over nlevgrnd, not nlevsoi

I've verified that ROOTR and ROOTR_COL have reasonable values (0-1) when use_hydrstress = .false. and ROOTR has reasonable values when use_hydrstress = .true.

**Comment by olyson** [comment]
I'm going to run a new control with ctsm1.0.dev074 (which can be compared with a simulation already complete with ctsm1.0.dev058, and then we can update our answer-changing tags page) and then run a simulation with the rootr fixes.

**Comment by olyson** [comment]
Diagnostics for ctsm1.0.dev074 compared to ctsm1.0.dev058 are [here](http://webext.cgd.ucar.edu/I20TR/clm50_ctsm10d074_2deg_GSWP3V1_hist/lnd/clm50_ctsm10d074_2deg_GSWP3V1_hist.1995_2014-clm50_ctsm10d058_2deg_GSWP3V1_hist.1995_2014/setsIndex.html)

Diagnostics for ctsm1.0.dev074 with rootr fix compared to ctsm1.0.dev074 are [here](http://webext.cgd.ucar.edu/I20TR/clm50_ctsm10d074_2deg_GSWP3V1_rootr_hist/lnd/clm50_ctsm10d074_2deg_GSWP3V1_rootr_hist.1995_2014-clm50_ctsm10d074_2deg_GSWP3V1_hist.1995_2014/setsIndex.html)

Both of these comparisons show minor differences.  In particular, changes in CH4-related fields are quite small.  rootr is used by activation of a "transpirationloss" switch (switch for activating CH4 loss from transpiration, transpiration loss assumes that the methane concentration in dissolved soil water remains constant through the plant and is released when the water evaporates from the stomata).  The comment in the code on this indicates that the impact is < 1 Tg CH4/yr.  Since global CH4PROD is about 650 Tg in the control simulation and doesn't change much in the rootr simulation, I guess these results are consistent with expectations.

**Comment by billsacks** [comment]
@olyson thanks for your work on this! Two questions:

(1) Can you review the comments I added in 3b3d9462 ? Are these comments correct?

(2) Is this ready to come to master, as far as you're concerned? If so, I'll run testing on it?

**Comment by olyson** [comment]
Yes, those comments are corirect.
Yes, I think it's ready to come to master, pending any failed testing of course, thanks.
