### ISSUE TITLE
Send roughness length to LILAC

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/CTSM#892]
WRF needs gridcell-average roughness length from CTSM. It looks to me like there are a few different roughness length variables in CTSM, and I'm not completely confident in my interpretation of how we should determine the gridcell-average value.

First off, there are separate roughness lengths for momentum, heat and moisture. @barlage thinks that we should probably send momentum roughness length; he isn't positive, but let's take that as a given for now.

I'm using the following code as guidance as to what roughness length is actually used over different landunits:

https://github.com/ESCOMP/CTSM/blob/b350e06e4615c124d3ef1d8f3f9831a1f8f3f402/src/biogeophys/FrictionVelocityMod.F90#L441-L490

I propose creating a new patch-level variable, perhaps named `z0m_actual_patch`, which holds the actual roughness length over each patch. Based on the above code and on code in LakeFluxesMod (and a bit of code analysis elsewhere), my best guess for setting this variable would be:

- soil / crop:
  - where frac_veg_nosno == 0: `z0m_acutal_patch(p) = z0mg_col(c)`
  - where frac_veg_nosno > 0: `z0m_actual_patch(p) = z0mv_patch(p)`
  - Notes: Need to get the z0mv value after CanopyFluxes, making sure that we set this only over points that were within the exposedvegp filter used in CanopyFluxes. (Perhaps we can do this by initially setting some new variable to z0mg(c) over all soil/crop patches, then overwriting it within the exposedvegp filter during or after CanopyFluxes.)

- urban: `z0m_actual_patch(p) = z_0_town(l)`
  - Note: @olyson can you particularly confirm this: is this correct for all urban patches?

- all others: `z0m_actual_patch(p) = z0mg_col(c)`
  - Note: For lakes, need to set `z0m_actual_patch` after `z0mg_col` is set in LakeFluxesMod

In particular, note that I think we can NOT use `z0mv_patch` over special landunits or (I think) vegetated landunits where `frac_veg_nosno == 0`: I think `z0mv_patch` has invalid values in those places.

@olyson I am co-assigning you because I'd love your input confirming or correcting my above proposal. I can do the actual coding myself.

**Comment by olyson** [comment]
That is the correct assignment for the roughness length for momentum for urban patches.  It is for the urban canyon as a whole.  One just has to make sure that the subgrid averaging of the patch values (roof, walls, canyon floor) works out appropriately.
I can confirm that the roughness lengths for vegetation are the same for momentum, and sensible and latent heat.  They do differ for bare soil or snow, and for different varieties of lake surfaces (unfrozen, frozen, snow-covered), as I'm sure you've noticed.

I'm not sure how the subgrid patches (i.e., soil, snow, surface water) use roughness length in their formulations, I will look into it.  It seems like they might each use different roughness lengths.  This would only have an effect on the bare ground patch for purposes of calculating the grid-average roughness length.  But would we need to average these subgrid patch roughness lengths to get the correct roughness length for the bare ground patch?

In general, depending on how it is used, roughness length may require a different averaging scheme than just a simple weighted average, e.g., an effective roughness length determined from the blending height method that is typically larger than one obtained from a linearly averaged roughness length.  I imagine Mike knows the details of how roughness length is used in WRF.

Otherwise, your proposal seems feasible.

**Comment by olyson** [comment]
Looks like the subgrid patches use the same roughness lengths.  Not sure that's technically correct, but currently don't have to worry about dealing with separate roughness lengths.

**Comment by billsacks** [comment]
@olyson thanks for your input. I'm just returning to this issue this afternoon. Am I correctly summarizing your reply as: My proposed patch-level assignments are correct, but I need to be careful about weighting the different patches both for (1) urban and (2) possibly a roughness length-specific averaging scheme?

For (1), from working through the scalings, I think it will work out if I do the p2g call with `c2l_scale_type = urbans`. Does that seem right to you?

For (2): @barlage , please let me know if you have any thoughts on doing a subgrid scaling that is specific to roughness length, as @olyson suggested:

> In general, depending on how it is used, roughness length may require a different averaging scheme than just a simple weighted average, e.g., an effective roughness length determined from the blending height method that is typically larger than one obtained from a linearly averaged roughness length. I imagine Mike knows the details of how roughness length is used in WRF.

**Comment by olyson** [comment]
Yes, that summary is correct.
Regarding 1), yes that scaling should be correct.
Regarding 2), and thinking more about it, linear average for the roughness length may be sufficient since the subgrid fluxes themselves are linearly averaged.

**Comment by billsacks** [comment]
Thank you again @olyson . I'll proceed with linear average of roughness lengths and will revise it later if @barlage has any further suggestions.

**Comment by billsacks** [comment]
I have implemented the above changes in d1f8a1d3 . @olyson if you have time to look at it, I'd welcome your double-checking of it – though I'm fairly confident that I have correctly captured the above plan, so I don't think you *need* to look at it.

**Comment by olyson** [comment]
I took a quick look.  Seems like that should work, thanks.

**Comment by billsacks** [comment]
Done on `lilac_cap` branch; closing.

**Comment by apcraig** [comment]
@billsacks, just a quick question about this implementation.  I will be pulling this mod into my version of CTSM for coupling with WRF.  We need to add the momentum z0 for coupling with WRF in RASM/NNA as well.  Thanks to Keith for pointing me to it (https://bb.cgd.ucar.edu/cesm/threads/gridcell-mean-z0m.5581/), I have an older version of the CTSM code that does not contain this modification yet.

I'm curious about your implementation.  In RASM, we are coupling the log(z0m) and that is mapped and merged in the coupler from multiple surfaces in typical fashion.  When the coupling variable, logz0, is passed into WRF, the z0 is computed by taking exp(logz0).  It turns out that mapping and merging logz0 rather than z0 improves the science by creating a more "correct" area weighted z0 average field based on how z0 is used in WRF.  Are you mapping and merging in the coupler in your applications?  If you are coupling, mapping, and merging z0 and not log(z0), is you might want to think about this issue.

Which leads to my actual question.  In this implementation, to aggregate to the gridcell, you are doing 

```
     call p2g(bounds, &
         frictionvel_inst%z0m_actual_patch (bounds%begp:bounds%endp), &
         lnd2atm_inst%z0m_grc              (bounds%begg:bounds%endg), &
         p2c_scale_type='unity', c2l_scale_type= 'urbans', l2g_scale_type='unity')
```
I suspect the right way to implement this is to also do the p2g average on the log(z0m_actual_patch).  I will probably modify this code to do that.  For our implementation, I will rename %z0m_grc to %logz0m_grc and just carry that thru to the coupling layer since we are passing the log(z0m) anyway.  So that would look something like

```
    logz0m(bounds%begp:bounds%endp) = log(frictionvel_inst%z0mv_actual_patch(bounds%begp:bounds%endp))
    call p2g(bounds, &
         logz0m, &
         lnd2atm_inst%logz0m_grc   (bounds%begg:bounds%endg), &
         p2c_scale_type='unity', c2l_scale_type= 'unity', l2g_scale_type='unity')

     ...

    l2x(index_l2x_Sl_logz0,i)    =  lnd2atm_inst%logz0m_grc(g)
```

where logz0m is just a local variable that stores the log of %z0mv_actual_patch so it can be passed into p2g.  Let me know whether you think I'm off the rails.  If I can help with anything or answer any questions if you decide to shift to log(z0), just let me know.

**Comment by billsacks** [comment]
@apcraig thanks for sharing your thoughts . What you're saying sounds reasonable, but I don't have much insight into this issue. I'm going to copy your comment into a new issue so that it can get more attention.
