### ISSUE TITLE
Should we use -no-megan when running CTSM via LILAC?

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/CTSM#924]
Should we use the `-no-megan` option to CTSM's build-namelist when running CTSM via LILAC? I have a sense that MEGAN involves some hand-shaking with the driver, and I'm not sure what's currently happening in the LILAC case. I know that CTSM's build-namelist allows a `-no-megan` option, but I'm not sure exactly what that does. Do we want to add that option (and/or do something else) when running CTSM's build-namelist for the sake of LILAC?

@mvertens @ekluzek @dlawrenncar can any of you weigh in on this?

**Comment by billsacks** [comment]
I should add: the current operation (as set up by @mvertens ) is that CTSM's build-namelist creates a `drv_flds_in` file with these contents:

```
&drydep_inparm
/
&megan_emis_nl
 megan_factors_file = '/Users/sacks/projects/cesm-inputdata/atm/cam/chem/trop_mozart/emis/megan21_emis_factors_78pft_c20161108.nc'
 megan_specifier = 'ISOP = isoprene', 'C10H16 = pinene_a + carene_3 + thujene_a', 'CH3OH = methanol', 'C2H5OH = ethanol',
         'CH2O = formaldehyde', 'CH3CHO = acetaldehyde', 'CH3COOH = acetic_acid', 'CH3COCH3 = acetone'
/
&fire_emis_nl
/
&carma_inparm
/
```

but then this file is deleted after running build-namelist. My sense is that specifying `-no-megan` will stop this file from being written (at least the `megan_emis_nl` portion of it), but I'm not sure if it has other consequences that we may or may not want.

**Comment by ekluzek** [comment]
Well, the story is a bit more complicated. But, the bottom line is that there's no real reason to limit MEGAN on or off for running with LILAC.

When you are running with CAM and you want the MEGAN species to interact with CAM chemistry, you need to use a shared MEGAN namelist for both. But, you can also run with MEGAN on for just CLM and have it disconnected from CAM chemistry. You might do that in order to just see the MEGAN emissions from the surface. 

That's still a valid thing to do with LILAC. You can legitimately run with MEGAN on, just to see the emissions it creates in an offline sense (not interacting with the atmosphere model in any way). In CESM if MEGAN is turned on, it will pass fields through the cpl from CLM to coupler and then to CAM. For LILAC you wouldn't need to pass these fields, unless you did the work to couple it to the chemistry in the atmosphere model. But, if you don't pass the fields there's no harm in generating them.

Outside of that running with -no-megan is a legit thing to do.

**Comment by dlawrenncar** [comment]
Seems like could run with -no-megan for now.  Would mainly be relevant when
we try to couple to WRF-Chem, which isn't first priority.

**Comment by billsacks** [comment]
Thanks @ekluzek and @dlawrenncar . For now I'll hard-code `-no-megan` in LILAC's buildnml, and we can generalize this later.
