### ISSUE TITLE
New initial conditions for 1979, 2000

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#992]
This is with discussions with Adam Herrington. We plan to add new finidat files for the ARCTIC and ARCTICGRIS refined mesh grids for 1979 for SP. And also new initial conditions for ne120 for 2000 with BGC.

**Comment by ekluzek** [comment]
The ne120 BGC finidat file would replace our current file for 2000. So most resolutions would be interpolating from the high resolution case. We should probably make sure that works out well for 1 and 2 degree. The thinking is that starting from higher resolution is probably fine. You do see aliasing when going from course resolution to fine.

**Comment by ekluzek** [comment]
With this setup SP simulations for 1979 or 2000 would match the ARCTIC or ARCTICGRIS grids. We'll probably need to figure out a way for the system to determine which one it should use.  The ARCTICGRIS is higher resolution so it should be used.

**Comment by adamrher** [comment]
I will submitting a 5 year ne120pg3 BGC_CROP F2000climo run today. It will use the finidat from the 1 degree year 2000 spun-up finidat. Provided this simulation ins't completely out of balance by year 5, then I will run a f09 and f19 BGC_CROP run for 10 or 20 years to make sure things don't look wacky. I would like some input on how to assess whether the relevant variables in BGC_CROP configuration are "in-balance" or "not-wacky." Should I use this spin-up stability script https://github.com/ESCOMP/CTSM/issues/821?

Provided everything checks out, the year 5 ne120pg3 restart file can be the new default finidat for year 2000 boundary condition compsets.

**Comment by adamrher** [comment]
Erik, just so we are on the same page, my ideal finidat's for both the ARCTIC grid and ARCTICGRIS grids would be this:

For F2000climo and FHIST, which both use SP, use my spun-up ARCTIC & ARCTCGRIS restart files as their finidat's. That is, ARCTIC would point to a spun-up ARCTIC restart & ARCTICGRIS would point a spun-up ARCTICGRIS restart.

For all BGC, BGC_CROP compset, and any SP compset that doesn't use year 2000 or 1979 boundary conditions, the ARCTIC / ARCTICGRIS grids should point to the default finidat.

**Comment by ekluzek** [comment]
Yes, you can use that spinup script. Note that Keith's version is mainly about getting the soil Carbon spunup. So for these purposes it's not necessarily a problem if it it doesn't show it as fully spunup. And we should probably make sure we get your updated script for SE grids into the repo for CESM2.2.0.

Your understanding and mine match, so this is good!

**Comment by dlawrenncar** [comment]
The reality is that 5 years won't be spunup for most BGC-related things.
Spinup script on such a short run probably won't really help.  I guess I am
inclined to just say, run it for 5 years and then use that file.  A few of
the biggest transients will be gone, but to get to 'equilibrium' for
something like Leaf Area Index would take at least more like 20 years.
Other quantities a lot longer than that.  The idea here is just to have
something that could be used that doesn't have an absolutely terrible
initial state.

**Comment by adamrher** [comment]
@dlawrenncar I'm not seeing a yr 2000 BGC finidat 0.9x1.25 for CLM5 in the repo:

/glade/p/cesmdata/inputdata/lnd/clm2/initdata_map/

 I see some for CLM45, but those won't work w/ CLM5, right?

**Comment by ekluzek** [comment]
It looks like the file we are using right now for 2000 for pretty much everything is this one:

clmi.I2000Clm50BgcCrop.2011-01-01.1.9x2.5_gx1v7_gl4_simyr2000_c180715.nc

CLM4.5 will work for CLM5.0, but you would want something that's spun up specifically for clm5.0.

**Comment by adamrher** [comment]
OK. Dave suggested I use a 0.9x1.25 version, but I think he may have been referring to those clm4.5 finidats. Ill just use that default 1.9x2.5 clm5.0 finidat.

**Comment by dlawrenncar** [comment]
No.  There should be several initial conditions for CLM5BGC-crop at
0.9x1.25 from CESM2 simulations.  Erik should be able to point you to them.

**Comment by adamrher** [comment]
stop the presses ... until I get word on where these yr 2000 0.8x1.25 restart files are.

**Comment by ekluzek** [comment]
I'll have to pull some from some CESM cases that I can then put in place that we can use. We have a bunch of options for 1850, but don't for 2000. So I need to get some from some historical cases.

**Comment by ekluzek** [comment]
Looks like I should take 2000 conditions from these cases...

i.e21.IHIST.f09_g17.CMIP6-land-hist.001
i.e21.IHIST.f09_g17.CMIP6-land-hist-cruNcep.001

for CLM5.0 GSWP3 and CRUNCEP forcing respectively...

and the clm file from this REFCASE for coupled

b.e21.BHIST.f09_g17.CMIP6-historical.010_v2

**Comment by adamrher** [comment]
I'm inclined to use the b compset year 2000 restart, since those I compset's you listed are forced by datm observations, and so probably not in ~balance with the CESM2 climate?

**Comment by ekluzek** [comment]
Yes, you should startup from the b case. I figure while I'm putting in place finidat files I might as well point to existing simulations.

**Comment by ekluzek** [comment]
Ahh, I closed it again!

**Comment by adamrher** [comment]
ok thx. I found that b compset case in the cesmdata/inputdata/cesm2_init/ folder, but it only has year 2015 restarts. In fact, I toggled through all the b.e21.BHIST.f09_g17.CMIP6-historical* cases and no of them have year 2000 restarts. Are the year 2000 restarts available anywhere or are these the only restarts that were saved?

The only 0.9x1.25 BGC year 2000 restart I can find in the cesm2_init folder is:

f.e21.FHIST_BGC.f09_f09_mg17.CMIP6-AMIP.001/2000-01-01

and a select few of these b.e20.BHIST.f09_g17.20thC.xxx where xxx is something like 190 or 297 that I think refer to all the run id during the development of cesm2 (and so probably not cesm2 proper).

**Comment by klindsay28** [comment]
Restart files for many CMIP6 experiments are on campaign storage at
/glade/campaign/collections/cmip/CMIP6/restarts
You might find what you need there.
As it is on campaign storage, it is not directly readable from cheyenne.
It is readable from casper.

**Comment by adamrher** [comment]
Thanks Keith. @ekluzek b.e21.BHIST.f09_g17.CMIP6-historical.010_v2 is not avail on campaign storage. But these two runs seems like good candidates:

b.e21.BHIST.f09_g17.CMIP6-historical.010 (which begins ~1850)

f.e21.FHIST_BGC.f09_f09_mg17.CMIP6-AMIP.001 (which begins a ~1950)

Since I'm going to run F2000climo_BGC (custom compset) to produce the new yr 2000 default finidat, I am leaning towards the f compset run to be the initial conditions.

Apologies for continuing to pester you on this Erik .... I just want to be certain to use the most appropriate initial conditions since the new default finidat will be widely used.

**Comment by ekluzek** [comment]
Yeah, for what you are doing it makes sense to start from the F compset that's closer to what you are doing. For the finidat files that CLM selects we currently can't distinguish between F and B compsets for how we choose files. So we've typically chosen a B compset version. CLM is driven by the atmospheric forcing, and there are differences for CAM between a B and F compset. So it makes sense to start from the case that's closest to the compset that you are going to run out.

**Comment by adamrher** [comment]
The spun-up finidat's for the ARCTIC & ARCTICGRIS grids in SP mode are here:

/glade/work/aherring/grids/var-res/ne0np4.ARCTIC.ne30x4/inic/cam6_2_017_FHIST_ne0np4.ARCTIC.ne30x4_mt12_7680pes_200423_1979bc-mg3-clubb_gamma-5yrs.clm2.r.1982-01-01-00000.nc

/glade/work/aherring/grids/var-res/ne0np4.ARCTICGRIS.ne30x8/inic/cam6_2_017_FHIST_ne0np4.ARCTICGRIS.ne30x8_mt12_7680pes_200426_mg3-1979bc-3yrs.clm2.r.1982-01-01-00000.nc

I ran the ne120pg3 F2000climo-BGC_CROP for three (3) years. I did run the spin-up stability script just to get a handle on how far out of balance it is. Plot is attached. TLAI and TWS are "not in equilibirum" with TLAI still shrinking & TWS still growing at year 3. I could run this out another two years to try to improve these two fields. Or we can just end here and call it a day. Thoughts?

The year 3 finidat is here:

/glade/scratch/aherring/cam6_2_022_F2000climoBgcCrop_ne120pg3_ne120pg3_mt13_7680pes_200430_mg3-clubb_gamma-2yrs/run/cam6_2_022_F2000climoBgcCrop_ne120pg3_ne120pg3_mt13_7680pes_200430_mg3-clubb_gamma-2yrs.clm2.r.0004-01-01-00000.nc

![cam6_2_022_F2000climoBgcCrop_ne120pg3_ne120pg3_mt13_7680pes_200430_mg3-clubb_gamma-2yrs_Spinup-pg1](https://user-images.githubusercontent.com/29961476/80919717-d467c480-8d28-11ea-8210-ceaf10cc11ec.png)
![cam6_2_022_F2000climoBgcCrop_ne120pg3_ne120pg3_mt13_7680pes_200430_mg3-clubb_gamma-2yrs_Spinup-pg2](https://user-images.githubusercontent.com/29961476/80919720-d893e200-8d28-11ea-8445-227da7de9675.png)

**Comment by wwieder** [comment]
Hello,
I have to admit, that I've only loosely been following this issue, but I think it depends on what you're wanting use these initial conditions file for, @adamrher. From what I recall, none of these configurations are going to be scientifically supported, it's mainly for testing the new dy-core in CAM?
Transient changes in TWS and LAI will effect climate. That said, I'd assume that you would not be in steady state in 1979 or 2000.  Has anyone created a 1850 initial conditions file to see how well we're in equilibrium with this high resolution grid?  If so, then maybe we can assume the transient changes seen here are just due to the historical forcing (and not related to the high resolution grid being used).

**Comment by dlawrenncar** [comment]
The units (or levels) are weird on those plots for all the carbon
variables.  The LAI looks like it is trending fairly strongly still.  Hard
to really interpret since we really don't usually use these scripts to
assess such short periods of spinup.  Not even really sure what I am
looking at.  Are we looking at annual averages over 3 years?  Anyway, if
you have computing time, another 2 years wouldn't hurt.  It won't be in
equilibrium by then, but in prior tests, we thought that a minimum
length to get to quasi LAI equilibrium is about 5 years, where quasi is
very quasi.

**Comment by adamrher** [comment]
I will run out another 2 years and reassess.

w.r.t the plot. Columns 1 an 3 have three data points in each panel for years 1, 2, 3. Columns 2 and 4 are supposed to contain 2 data points in each panel, which should probably be years 1.5 and 2.5, but are instead assigned x-values of year 1 and 2. Column 4 panels makes sense that the lines are flat because the trend seems almost identical between years 1, 2 and 3. Column 2 panels do not make sense because the trend is not linear for all three years, and so the change in time should not be flat.

@wwieder thanks for the feedback. The ARCTIC stuff is for new grids in the se-dycore. More on that here: https://github.com/ESCOMP/CTSM/issues/994 ... pictures of these new grids are in the CAM git issue linked there. Those finidats are spun-up with perpetual 1979 inic, and are to be used for 1979 / 2000 SP compsets when running those particular grids. This is all at the level of functional support still. This ne120pg3 business is to replace the default yr 2000 finidat b/c using the current 2 deg FV finidat aliases the fields as a result of the interpolation to the target grid at initialization. These will be widely used (any yr 2000 run) and so I think it's worth running at least another two years to see if we can improve on TWS and TLAI.

**Comment by adamrher** [comment]
I ran out another 2 years, so a total of 5 years. TLAI appears to have equilibrated based on the thresholds in the script. TWS is improved, but not equilibrated. GPP looks good'ish. Carbon, not so much. Snow is still growing but as we discussed, this is only relevant to those interested in the surface mass balance in antarctica / greenland, and this doesn't impact climate. 

Does this pass muster or shall I run this out longer?

![cam6_2_022_F2000climoBgcCrop_ne120pg3_ne120pg3_mt13_7680pes_200430_mg3-clubb_gamma-2yrs_Spinup-pg1a](https://user-images.githubusercontent.com/29961476/81129763-aa69fa00-8f02-11ea-82f2-5bbb9bda94a9.png)

![cam6_2_022_F2000climoBgcCrop_ne120pg3_ne120pg3_mt13_7680pes_200430_mg3-clubb_gamma-2yrs_Spinup-pg2a](https://user-images.githubusercontent.com/29961476/81129767-ae961780-8f02-11ea-9b44-25147bb3d1da.png)

**Comment by adamrher** [comment]
I changes the filenames for the 1979/2000 SP finidats for ARCTIC & ARCTICGRIS grids. They are now:

/glade/work/aherring/grids/var-res/ne0np4.ARCTIC.ne30x4/inic/FHIST_ARCTIC_ne30x4_mt12_1979bc-mg3.clm2.r.-01-01-00000_c200424.nc

/glade/work/aherring/grids/var-res/ne0np4.ARCTICGRIS.ne30x8/inic/FHIST_ARCTICGRIS_ne30x8_mt12_1979bc-mg3.clm2.r.01-01-00000_c200428.nc

**Comment by wwieder** [comment]
If you're wanting to run these in SP mode why are you bothering to spin up the BGC (carbon cycle) state?  Seems like you'd just want TWS and H2O snow initial condition.

Even for these water cycle metrics, I wouldn't necessarily expect these fields to be in steady state in the late 20th century, and as you say shouldn't influence surface climate if it's just changing over non-vegetated areas.

**Comment by adamrher** [comment]
@dlawrenncar please see the above 5 year plot. @wweider, here is an explanation of what we are trying to do:

There are two separate issues. I wanted to provide good spun-up inic for the ARCTIC / ARCTICGRIS grids in SP-mode, so that users can run F2000climo and FHIST out of the box for the cesm2.2 release. The spin-up consisted of resetting the snowpack, run for 20 years, then forcing CTSM standalone for ~500 years via cycling over the 20 year forcing. Then I ran coupled again for a few years and dumped out the restarts. That's the inic I've pointed to above.

The other issue is that with all these new grids now being supported at the functional level (CONUS grid, all the FV3 grids, etc ... ), the current approach to initializing CTSM, i.e., maps a spun-up 2 deg FV finidat to the target grid at initialization, results in grid aliasing if running at a higher resolution than 2 deg. See for example monthly mean H2OSNO in the first month of a ne120pg3 simulation:

![temp_postamps_namerica_H2OSNO_yr1-jan](https://user-images.githubusercontent.com/29961476/81189909-644d7e80-8f74-11ea-8672-a5ba02e0bc18.png)

The reason I'm doing a first-order stab at a spin-up for BGC using ne120pg3 is to replace the FV 2deg year 2000 finidat, so that this aliasing is no longer an issue ... At least in as much as people are running F2000climo or FHIST, which is most commonly ran with expensive grids. Note that FHIST defaults to the year 2000 finidat. The bar for replacing the year 2000 finidat is that it has to work for both SP and BGC. Hence, I'm running BGC.

You bring up a good point that many fields would be expected to be out of balance b/c I'm branching off of a transient, historical run. If you read through the thread, you'll see why we decided to go this route ... basically b/c we couldn't find a FV 1deg spun-up year 2000. Perhaps in hindsight I should have ran ne120pg3 w/ the current FV 2deg year 2000 finidat .. the reason we decided not to is b/c we are running a 0.25 deg grid, and felt that the 1 deg inic would be more appropriate.

**Comment by dlawrenncar** [comment]
I think for the purposes of this IC file, this looks good enough.

**Comment by adamrher** [comment]
Great. The year 2000 BGC_CROP ne120pg3 year 6 restart is here:

/glade/work/aherring/grids/uniform-res/ne120np4.pg3/inic/F2000climoBgcCrop_ne120pg3_ne120pg3_mt13_7680pes.clm2.r.01-01-00000_c200506.nc

And again, the spun-up 1979 SP ARCTIC & ARCTICGRIS restarts are here:

/glade/work/aherring/grids/var-res/ne0np4.ARCTIC.ne30x4/inic/FHIST_ARCTIC_ne30x4_mt12_1979bc-mg3.clm2.r.-01-01-00000_c200424.nc

/glade/work/aherring/grids/var-res/ne0np4.ARCTICGRIS.ne30x8/inic/FHIST_ARCTICGRIS_ne30x8_mt12_1979bc-mg3.clm2.r.01-01-00000_c200428.nc

Unless there are any objections, these are the three files required to complete this issue.

**Comment by adamrher** [comment]
@fischer-ncar I was able to complete 1 of the 3 tasks in this issue: changing the default finidat for all year 2000 runs in namelist_defaults: /glade/u/home/aherring/src/cam6_2_029/components/clm/bld/namelist_files/namelist_definition_ctsm.xml

@ekluzek Issues 2 and 3 are setting the finidat for ARCTIC and ARCTICGRIS in year 2000 SP runs. I am having an issue because the finidat's I'm pointing to error out due to a mismatch in landunit dimension sizes. So to get them to work, I have to use_init_interp = T.

Do I have to add an init_interp_attributes entry for the two grids, and then add a findat entry like this:
<img width="1339" alt="Screen Shot 2020-06-05 at 4 17 49 PM" src="https://user-images.githubusercontent.com/29961476/83926941-8b9c9480-a748-11ea-8050-9dd9d041f79c.png">

But with hgrid and mask set to artic grids, and other values set to that used in SP mode?

**Comment by ekluzek** [comment]
It should figure out the closest finidat file and then turn init_interp on since it can't match the grid exactly. So you shouldn't have to add an extra entry for it. You will need an entry for Sp as well as Bgc and also Bgc-Crop that it can match though.

Is that the grid it should match? If so you need an additional entry that's appropriate for 2000 SP.

**Comment by adamrher** [comment]
@ekluzek here are the three finidats per our conversation:

For all year 2000 F/B compsets (replacing the fv2deg file):
/glade/work/aherring/grids/uniform-res/ne120np4.pg3/inic/F2000climoBgcCrop_ne120pg3_ne120pg3_mt13_7680pes.clm2.r.06-01-00000_c200506.nc

For year 2000 F/B -nocrop compsets for the ARCTIC grid only:
/glade/work/aherring/grids/var-res/ne0np4.ARCTIC.ne30x4/inic/FHIST_ARCTIC_ne30x4_mt12_1979bc-mg3.clm2.r.1982-01-01-00000_c200424.nc

For year 2000 F/B -nocrop compsets for the ARCTICGRIS grid only:
/glade/work/aherring/grids/var-res/ne0np4.ARCTICGRIS.ne30x8/inic/FHIST_ARCTICGRIS_ne30x8_mt12_1979bc-mg3.clm2.r.1982-01-01-00000_c200428.nc
