### ISSUE TITLE
'Cap' in GPP at high light levels

### ISSUE THREAD

**Issue by dlawrenncar** [ESCOMP/CTSM#993]
In CLM5 and prior versions, maximum hourly values of GPP are not as high as in observations at at least some tower sites, definitely at US-UMB site.  See attached figures from  Gretchen Keppel-Aleks. 

![Screen Shot 2020-04-24 at 2 01 26 PM](https://user-images.githubusercontent.com/20978772/80252213-1e1f2380-8634-11ea-95bc-5ffffd911123.png)
![Screen Shot 2020-04-24 at 2 01 13 PM](https://user-images.githubusercontent.com/20978772/80252217-1f505080-8634-11ea-8c03-6a80546d8470.png)

**Comment by dlawrenncar** [comment]
Note that Gretchen is hypothesizing that the absence of these high GPP values is contributing to the weaker than observed interannual GPP/Carbon cycle variability that we see in CLM5 (and to a lesser degree in prior model versions).

**Comment by dlawrenncar** [comment]
From email discussion:

Gordon:  fpns and theta_psii are the two parameters I mentioned last week that control the light response curve for C3 plants. (C4 plants use a different relationship). fnps = 0.15, but an alternative value in some models is 0.3. theta_psii = 0.7, but in the multilayer canopy I use 0.9.

Attached is a figure from my modeling textbook, which shows the effects of these parameters on photosynthesis. I use somewhat different notation than CLM:

book    = CLM
-------    = -------------
theta_j  = theta_psii
phi_psii = 1 - fnps

The value for theta_j (theta_psii) has the biggest influence on photosynthesis. The larger value (0.9) increases photosynthesis for the same amount of PAR, but then the Rubisco-limited rate (dashed line) kicks in at lower PAR. Above this amount, photosynthesis is independent of PAR. A smaller value (0.7) has lower photosynthesis so that the Rubisco-limited rate becomes limiting at higher PAR. How this plays out in terms of canopy GPP is unclear, but it is worth trying the value for 0.9. It may be that the biggest signal is not in mean GPP but in the functional relationship of GPP with solar radiation, or even the sensitivity of GPP to direct/diffuse radiation.
![image (3)](https://user-images.githubusercontent.com/20978772/80252534-aac9e180-8634-11ea-9bf0-f017f02899d7.png)

**Comment by dlawrenncar** [comment]
From email discussion: 

Danica: Yes, I think these are good parameters to add to the parameter perturbation experiment. We might also want to consider testing the sensitivity of two other aspects of photosynthesis calculations: 

1) Parameters related to photosynthetic acclimation. Some of these are constants included within the equations in CLM (e.g., see lines 3166-7 in PhotosynthesisMod.F90), and other related parameters are hardcoded (e.g., see lines 2791-2807). 
2) TPU. This is a highly uncertain aspect of photosynthesis (set to 1.67 * Vcmax), but note that I already wrote a paper on the sensitivity of this parameter (published in ERL, 2018).

**Comment by dlawrenncar** [comment]
From email discussion:

In response to question from Dave about what determines Rubisco-limited rate, Gordon replied:
That's where Vcmax comes into play. It sets the dashed line. Higher values of Vcmax will give a higher light-saturated photosynthetic rate. The other parameters (fnps, theta_psii) matter when photosynthesis is not light saturated. So, too, does Jmax (but in CLM that is calculated by LUNA, not a parameter). It is hard to say how all this plays out at the canopy scale. It's likely that the sunlit canopy is light saturated, but the shaded canopy is not. But then there are a lot more shaded leaves than sunlit leaves.

**Comment by alistairrogers** [comment]
Based on a paper Anthony is leading I would try changing thetaCJ and thetaIP to 0.999 (Eqn 9.6 in the tech note) this would essentially eliminate CBGB smoothing of Ac, Aj and Ap (Dave the impact will be highly analogous to your thetaJ figures above).

For diagnostic purposes:- 

1. Calculate the effective Vc,max and Jmax
2. Double Vc,max (probably through doubling Ncb)
3. Double Jmax:Vcmax ratio

**Comment by rosiealice** [comment]
Also given we already did that in FATES, one could in principle look at whether FATES has the same problems, which would be interesting to know in general as well...

**Comment by dlawrenncar** [comment]
Agreed.  I was already wondering whether or not FATES would show similar
issue.  We have the forcing data to be able to run at the US-UMB site if
that was something that would be possible with FATES.  Might be outside of
the FATES climate zone where PFTs are well-parameterized, but Rosie
obviously would know better about that.  Something to discuss on Thursday.

**Comment by adrifoster** [comment]
> Also given we already did that in FATES, one could in principle look at whether FATES has the same problems, which would be interesting to know in general as well...

I was thinking it would also be interesting to look at these relationships at different sites with differences in vegetation structural diversity. We might expect a more mixed response to diffuse fraction in a mixed-age, mixed-species stand like at UMBS because different shaped tree crowns are better able to absorb different levels of diffuse/direct light, whereas in a more even-aged, low species diversity stand we might expect a stronger relationship with diffuse fraction.

We could try to leverage the various NEON sites which have both tower and lidar/forest inventory data and compare to FATES?

**Comment by wwieder** [comment]
Thanks @alistairrogers, @xuchongang, @walkeranthonyp, @rosiealice, @danicalombardozzi for your comments and suggestions today.  I also found this [discussion in FATES](https://github.com/NGEET/fates/issues/472) helpful & similar to part of our conversation today.  I'm going to summarize suggestions from the meeting here. Please modify or add to this thread as is warranted.

Ideas to test, not necessarily solutions.  A goal is to try to understand where the limitation is sourcing from LUE (LUNA parameters), CBGB scaling, light saturated photosynthesis, or canopy scaling (including light profiles through the canopy).

- [ ] Vcmax (LUNA). The Ali (2015) paper talks about `tc,j0`, I think this is the same parameter https://github.com/ESCOMP/CTSM/blob/3c31fb41bf55de43e71637aaa0bd7c34752332f1/src/biogeophys/LunaMod.F90#L77

- [ ] Jmax (LUNA).  
https://github.com/ESCOMP/CTSM/blob/3c31fb41bf55de43e71637aaa0bd7c34752332f1/src/biogeophys/LunaMod.F90#L75
https://github.com/ESCOMP/CTSM/blob/3c31fb41bf55de43e71637aaa0bd7c34752332f1/src/biogeophys/LunaMod.F90#L76
**Note** For Arctic bugs #990 & #961, `Jmaxb1` was these lowered for CLM5 for testing from 0.17 in the Ali paper

- [ ] Jmax:Vcmax ratio 
Not sure how to do this @xuchongang unless with the two changes, above?

- [ ] CBGB scaling (Collatz), Smoothing parameterization (including TPU) may be important.
`theta_ip = 0.95_r8` &  `theta_cj(p) = 0.98_r8` **NOTE** theta_cj is different for C3/C4. @alistairrogers suggested running with both of  these set higher (0.999)

- [ ] Leaf level light response of photosynthesis: (still have some light saturation, hard cap on leaf-level photosynthesis
`fnps = 0.15_r8` & `theta_psii = 0.7_r8`
Try increasing `theta_psii = 0.9`, seems like fnps may already be high enough?

- [ ] CANOPY SCALE
Leaf orientation and angle, see new parameter files (leaves too flat, (chi_)  
`pftcon%xl` used in [SurfaceAlbedoMod](https://github.com/ESCOMP/CTSM/blob/master/src/biogeophys/SurfaceAlbedoMod.F90)
For xl, -1 means vertical leaf, 1 is horizontal leaf, 0 is random orientation.  Note that new optical properties in issue #807 move xl values towards higher (closer to 1) for most PFTs.

**Comment by alistairrogers** [comment]
Thanks Will and Dave for invitation to join the conversation. I'll be interested to stay in touch and hear what you learn. 

I suspect changing Theta_psii will not have a large effect so maybe put that one lower down your list. Theta_psii at 0.7 seems reasonable to me and is widely used in many TBMs. It allows a gradual transition from light limited to carboxylation limited photosynthesis. Cranking it up to 0.9 probably won't help much as your low GPP is at saturating irradiance rather than in the transition zone between light limited and light saturated photosynthesis.

Also don't forget to try doubling Vcmax (not on your list immediately above Will). It would be easy to implement and in my mind all signs point to low carboxylation capacity as the culprit.

**Comment by dlawrenncar** [comment]
We will include it.  It's actually #1 in list, which should read 'double
Vcmax, rather than just Vcmax.  One reason, though, that we are not as
focused on this is that it looks like CLM prediction of Vcmax from LUNA is
not 'too bad'. See Table 3 in CLM5 overview paper.
https://agupubs.onlinelibrary.wiley.com/doi/epdf/10.1029/2018MS001583%4010.1002/%28ISSN%291942-2466.CESM2

But, either way at this point, we are just exploring sensitivity, so it is
worth a try.

**Comment by walkeranthonyp** [comment]
Seconding @alistairrogers - it was great to chat with you about this. Thanks for the invitation! I hope it's useful in the end and looking forward to seeing the results of your investigations. 

Also to add (as I didn't see it in your list @wwieder) that it'd be really useful to see GPP plotted against APAR.

**Comment by danicalombardozzi** [comment]
I agree with @alistairrogers that the problem seems to be canopy-scale carboxylation. One thing to note, however, is that the calculation of Vcmax is quite different between CLM4.5 and CLM5, and we were seeing similar caps to photosynthesis in CLM4.5. This also leads me to wonder about the influence of canopy scaling, as I'm not sure whether that has changed as much. It's worth working through each of the steps that @wwieder outlined above.

**Comment by walkeranthonyp** [comment]
> * `pftcon%xl` used in [SurfaceAlbedoMod](https://github.com/ESCOMP/CTSM/blob/master/src/biogeophys/SurfaceAlbedoMod.F90)
>   For xl, -1 means vertical leaf, 1 is horizontal leaf, 0 is random orientation.  Note that new optical properties in issue #807 move xl values towards higher (closer to 1) for most PFTs.

I'm probably missing something but I'm not used to this way of expressing `xl` given that when leaf angle is translated into an extinction coefficient, random leaf angle distribution is 0.5, horizontal 1, and vertical 0. In any case, one way to hack clumping into the canopy if you don't have a separate parameter would be to multiply the extinction coefficient by a clumping factor 0-1 where 1 is no clumping and 0 infinite clumping (i.e. zero light interception). That could be done through `xl` but I'm not sure how `xl` should be adjusted, reduce it to so that `xl < 0` I guess.

**Comment by walkeranthonyp** [comment]
https://www.geosci-model-dev-discuss.net/gmd-2019-335/gmd-2019-335.pdf

This paper is also very relevant. Different ecosystem (Costa Rican forests) but similar(ish) results. See Fig 4 especially. They plot against APAR and find that saturation GPP is good but that the slope is way too high and they correct by increasing `fnps` (if I'm getting my parameter names correct) so that less absorbed light ends up stimulating electron transport.

**Comment by alistairrogers** [comment]
@dlawrenncar thanks for the reference. Is this your preferred citation for CLM5? 

I see that your Vcmax25s largely match K2009. The problem with CBGB smoothing is that the K2009 Vcmax25s are fit from datasets that did not include smoothing in their fitting approach. To achieve the same A as a model without CBGB smoothing would require a larger Vcmax.

**Comment by dlawrenncar** [comment]
Yes.  That is the standard reference for CLM5, though depending on topic,
there are a lot of other CLM5 papers out there (Rosie, Gordon, Will,
Danica, Daniel all have papers covering various related topics!)

**Comment by wwieder** [comment]
@alistairrogers , in your suggestion to double Vc,max I think this will also increase Jmax.  This this OK?   @xuchongang is there any way to modify only Vcmax, or is this done by changing `Wc2Wjb0`

**Comment by wwieder** [comment]
For what its worth NEON includes data on PAR as well as direct  and diffuse fractions, allowing us  to test  this at multiple sites down the road!

**Comment by wwieder** [comment]
To summarize, here's the list of parameters we're focusing on:
- Jmaxb0
- Jmaxb1
- Wc2Wjb0
- theta_ip
- theta_cj
- fnps [* may not be critical]
- theta_psii [* may not be critical]
- pftcon%xl

**Comment by dlawrenncar** [comment]
I wonder if it would make sense to relax the limit on wc2wjb0 in any next set of parameter perturbations.  Chongang implied that it may not be necessary or even appropriate.

**Comment by alistairrogers** [comment]
I was really struggling to map the LUNA parameters to traditional FvCB parameters on the fly. If I understood it correctly wc2wjb0 controls the JVratio. See fig 5(c) in Kumarathunge et al (2019) for the global range of JVratio25. Checking that the JVratio25 is close to that predicted for the growth temperature makes sense. 

[Kumarathunge_et_al-2019-New_Phytologist.pdf](https://github.com/ESCOMP/CTSM/files/4664669/Kumarathunge_et_al-2019-New_Phytologist.pdf)

**Comment by walkeranthonyp** [comment]
Agreed, it would be good to check site values of Vcmax and Jmax (JV), and try to run CLM without LUNA and the site values of V and J. If that's possible. 

Also, this may be obvious, sorry if so. If I remember right high JV was decreasing the GPP cap. You wouldn't expect that if V and J 25 were simply fixed parameters. But LUNA is trying to optimise a fixed quantity of N, so higher JV means a higher fraction of N in J per unit V. Assuming the amount of leaf N is fixed (which it isn't i guess in CLM5.0, but for simplicity), then that means higher JV results in lower V, and therefore a lower cap given the cap is V limited (light saturated photosynthesis).

**Comment by alistairrogers** [comment]
@wwieder Hi Will could you point me to the relevant bit of code or confirm the units of Ncb in the code. (see Eqn 2.10.2 in the tech note and the legend for Table 2.10.1) Ncb is listed as having units of gN associated with Rubisco m-2 leaf area and also as gN in Rubisco g-1 N in the leaf. I'm in the middle of a related conversation with Jenifer Holm and this could shed some light on this issue. There's a potential -23% error in Vcmax25 but it might just be an error in the tech note.

**Comment by wwieder** [comment]
The code is labeled similarly
https://github.com/ESCOMP/CTSM/blob/b0547837413ee9fe5e8039da5814882b4faf4cbd/src/biogeophys/LunaMod.F90#L874

Here's where it's calculated
https://github.com/ESCOMP/CTSM/blob/b0547837413ee9fe5e8039da5814882b4faf4cbd/src/biogeophys/LunaMod.F90#L919

**Comment by alistairrogers** [comment]
Thanks Will,
The CLM5 tech note lists PFT specific parameters for Ncb that are equal to the FLNR values for these PFTs in CLM4.5 (Jenifer spotted that one) but the units are different. The units in the code are consistent with calculating Vcmax but if you use the values for Ncb in table 2.10.1 in the tech note you get a lower Vcmax because you haven't yet multiplied by Na. This wouldn't be obvious for Na close to 1 but for BDT-temperate you would underestimate Vcmax25, that would limit CO2 assimilation at high irradiance. It would be useful to see PFT specific values for FNCa and PNcbold to see if the tech note matches the code.
